/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import AlgebraicGroups.Algebra.AlgebraicallyClosedCommonZero
public import AlgebraicGroups.Algebra.LocalizedCoordinateQuotient
public import AlgebraicGroups.Algebra.FinitePolynomialLocalizationDimension
public import AlgebraicGroups.Algebra.TensorProduct.Pi
public import AlgebraicGroups.Algebra.Smooth
public import AlgebraicGroups.Algebra.SymmetricAlgebra
public import AlgebraicGroups.Algebra.SymmetricAlgebraPoints
public import AlgebraicGroups.Algebra.PrimitivePowerHopfIdeal
public import AlgebraicGroups.Algebra.SpecialLinearCoordinateRing
public import AlgebraicGroups.Algebra.UnitriangularCoordinateRing
public import AlgebraicGroups.Algebra.UnitriangularBaseChange
public import AlgebraicGroups.Algebra.UnitriangularBaseChangeCoherence
public import AlgebraicGroups.Algebra.MonoidAlgebraPrimitive
public import AlgebraicGroups.Category.Extensive
public import AlgebraicGroups.Category.EquivalenceRelation
public import AlgebraicGroups.Category.Grp.FilteredColimits
public import AlgebraicGroups.FieldTheory.GeometricallyReduced
public import AlgebraicGroups.GroupObject.Characteristic
public import AlgebraicGroups.GroupObject.Coset
public import AlgebraicGroups.GroupObject.EffectiveEpi
public import AlgebraicGroups.GroupObject.FunctorCategory
public import AlgebraicGroups.GroupObject.Hom
public import AlgebraicGroups.GroupObject.KernelTorsor
public import AlgebraicGroups.GroupObject.Quotient
public import AlgebraicGroups.GroupObject.SplitKernelProduct
public import AlgebraicGroups.GroupObject.SplitKernelSemidirect
public import AlgebraicGroups.GroupObject.Translation
public import AlgebraicGroups.GroupScheme.Additive
public import AlgebraicGroups.GroupScheme.Vector
public import AlgebraicGroups.GroupScheme.VectorProduct
public import AlgebraicGroups.GroupScheme.MatrixEndAdditive
public import AlgebraicGroups.GroupScheme.MatrixEndScheme
public import AlgebraicGroups.GroupScheme.AdditivePowerQuotient
public import AlgebraicGroups.GroupScheme.ArtinSchreierTwistedLine
public import AlgebraicGroups.GroupScheme.ClosedPoints
public import AlgebraicGroups.GroupScheme.Commutative
public import AlgebraicGroups.GroupScheme.ComponentGroup
public import AlgebraicGroups.GroupScheme.ComponentQuotient
public import AlgebraicGroups.GroupScheme.ComponentSchemeMap
public import AlgebraicGroups.GroupScheme.CosetDimension
public import AlgebraicGroups.GroupScheme.CosetQuotient
public import AlgebraicGroups.GroupScheme.Dimension
public import AlgebraicGroups.GroupScheme.FiniteConstant
public import AlgebraicGroups.GroupScheme.FiniteConstantPoints
public import AlgebraicGroups.GroupScheme.FiniteTriangularGeometry
public import AlgebraicGroups.GroupScheme.FiniteTypePoints
public import AlgebraicGroups.GroupScheme.FrobeniusTwistedLine
public import AlgebraicGroups.GroupScheme.FrobeniusTwistedLineBaseChange
public import AlgebraicGroups.GroupScheme.GeneralLinear
public import AlgebraicGroups.GroupScheme.Diagonal
public import AlgebraicGroups.GroupScheme.DiagonalDimension
public import AlgebraicGroups.GroupScheme.DiagonalProduct
public import AlgebraicGroups.GroupScheme.Unitriangular
public import AlgebraicGroups.GroupScheme.UnitriangularGeometry
public import AlgebraicGroups.GroupTheory.UpperTriangular
public import AlgebraicGroups.GroupScheme.UpperTriangular
public import AlgebraicGroups.GroupScheme.UpperTriangularDimension
public import AlgebraicGroups.GroupScheme.UpperTriangularSplitKernel
public import AlgebraicGroups.GroupScheme.UpperTriangularSchemeProduct
public import AlgebraicGroups.LinearAlgebra.Matrix.UpperTriangularIndices
public import AlgebraicGroups.GroupTheory.UnitriangularCentralFiltration
public import AlgebraicGroups.GroupTheory.UnitriangularSuperdiagonalQuotients
public import AlgebraicGroups.GroupTheory.UnitriangularNilpotencyClass
public import AlgebraicGroups.GroupTheory.UnitriangularLowerCentralSeries
public import AlgebraicGroups.GroupTheory.UnitriangularDerivedSeries
public import AlgebraicGroups.GroupTheory.UnitriangularExponent
public import AlgebraicGroups.GroupScheme.GeneralLinearDeterminant
public import AlgebraicGroups.GroupScheme.GeneralLinearDeterminantProduct
public import AlgebraicGroups.GroupScheme.GeneralLinearDeterminantConjugation
public import AlgebraicGroups.GroupScheme.GeneralLinearDeterminantSection
public import AlgebraicGroups.GroupScheme.GeneralLinearModule
public import AlgebraicGroups.GroupScheme.GeneralSpecialLinearDimension
public import AlgebraicGroups.GroupScheme.GeneralSpecialLinearGeometricIntegral
public import AlgebraicGroups.GroupScheme.GeneralSpecialLinearSmooth
public import AlgebraicGroups.GroupScheme.IdentityComponent
public import AlgebraicGroups.GroupScheme.IdentityComponentBaseChange
public import AlgebraicGroups.GroupScheme.InfinitesimalAdditive
public import AlgebraicGroups.GroupScheme.InfinitesimalAdditiveNonisomorphism
public import AlgebraicGroups.GroupScheme.InfinitesimalAdditiveTranslation
public import AlgebraicGroups.GroupScheme.InfinitesimalAdditiveZero
public import AlgebraicGroups.GroupScheme.Multiplicative
public import AlgebraicGroups.GroupScheme.PointwiseSubgroup
public import AlgebraicGroups.GroupScheme.QuotientSheaf
public import AlgebraicGroups.GroupScheme.Reduction
public import AlgebraicGroups.GroupScheme.ReducedIdentityComponent
public import AlgebraicGroups.GroupScheme.RootsOfUnity
public import AlgebraicGroups.GroupScheme.Separated
public import AlgebraicGroups.GroupScheme.SpecialLinearKernel
public import AlgebraicGroups.GroupScheme.SpecialLinearModule
public import AlgebraicGroups.GroupScheme.Smooth
public import AlgebraicGroups.LinearAlgebra.Basis.Semilocal
public import AlgebraicGroups.LinearAlgebra.FiniteProjective.Charpoly
public import AlgebraicGroups.RingTheory.Equalizer
public import AlgebraicGroups.RingTheory.FaithfullyFlat
public import AlgebraicGroups.RingTheory.LocalInfiniteResidueExtension
public import AlgebraicGroups.RingTheory.Semilocal
public import AlgebraicGroups.Scheme.Artinian
public import AlgebraicGroups.Scheme.AffineRelationQuotient
public import AlgebraicGroups.Scheme.ClopenAffine
public import AlgebraicGroups.Scheme.EquivalenceRelationRank
public import AlgebraicGroups.Scheme.EquivalenceRelationRankAffine
public import AlgebraicGroups.Scheme.EquivalenceRelationRankEqualizer
public import AlgebraicGroups.Scheme.EquivalenceRelationIntegrality
public import SchemeProperties.ConnectedComponents
public import AlgebraicGroups.Scheme.FiniteCoproduct
public import AlgebraicGroups.Scheme.GeometricallyReduced
public import AlgebraicGroups.Scheme.GlobalSections
public import AlgebraicGroups.Scheme.JointlySchemeTheoreticallyDominant
public import AlgebraicGroups.Scheme.Reduction
public import AlgebraicGroups.Scheme.Smooth
public import AlgebraicGroups.Topology.KrullDimension

/-!
The aggregate exposes the finite upper-unitriangular Hopf quotient, affine
group scheme and underlying affine geometry, native central filtration,
successive quotients, exact nilpotency class under nontriviality, the
all-stage lower-central-series identification and the derived series
and sharp prime-power exponent bounds for the native point group alongside
the general- and special-linear constructions.
-/
