/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import AlgebraicGroups.GroupScheme.Additive
public import Mathlib.RingTheory.AdjoinRoot
public import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# Additive power quotients

For a commutative ring `K` and any natural number `N`, the quotient of the
additive-group coordinate ring by the `N`-th power of its distinguished
coordinate is the polynomial quotient `K[X]/(X ^ N)`. The presentation works
over the zero ring and for `N = 0` or `N = 1`. When `K` is nontrivial and
`1 < N`, the distinguished coordinate survives in the quotient.

This is an equivalence of `K`-algebras; it does not assert compatibility with
any coalgebra or Hopf-algebra structure.

The characteristic-power quotient over a field is the coordinate presentation
in Milne's *Algebraic Groups*, item 2.5. The algebra equivalence here holds for
every natural power and every commutative base; its nonvanishing theorem needs
`1 < N` and a nontrivial base.

## References

- James S. Milne, *Algebraic Groups* (2017), item 2.5, p. 40 (the
  characteristic-power polynomial quotient over a field).
- Mathlib, `Mathlib.RingTheory.Ideal.Quotient.Operations` and
  `Mathlib.RingTheory.AdjoinRoot` (transporting quotients across an algebra
  equivalence and the distinguished quotient root).
- `AlgebraicGroups.GroupScheme.Additive` (the additive-coordinate polynomial
  presentation used to transport the quotient).
-/

public section

noncomputable section

universe u

namespace AlgebraicGeometry

/-- The ideal generated by a power of the additive group's coordinate. -/
abbrev additivePowerIdeal (K : Type u) [CommRing K] (N : ℕ) :
    Ideal (additiveGroupCoordinateRing K) :=
  Ideal.span {(additiveGroupCoordinate K) ^ N}

/-- The coordinate ring cut out by the `N`-th power of the additive coordinate. -/
abbrev additivePowerCoordinateRing (K : Type u) [CommRing K] (N : ℕ) :=
  additiveGroupCoordinateRing K ⧸ additivePowerIdeal K N

/-- The image of the additive coordinate in its power quotient. -/
@[expose] def additivePowerCoordinate (K : Type u) [CommRing K] (N : ℕ) :
    additivePowerCoordinateRing K N :=
  Ideal.Quotient.mk (additivePowerIdeal K N) (additiveGroupCoordinate K)

/-- The algebraic presentation of the quotient by a coordinate power, with no
nontriviality or positivity assumption on `K` or `N`. At `N = p ^ m` over a
characteristic-`p` field, this is the algebra presentation in Milne's
*Algebraic Groups*, item 2.5, not an equivalence of Hopf algebras. -/
@[expose] def additivePowerCoordinateAlgEquiv (K : Type u) [CommRing K] (N : ℕ) :
    additivePowerCoordinateRing K N ≃ₐ[K]
      AdjoinRoot ((Polynomial.X : Polynomial K) ^ N) :=
  Ideal.quotientEquivAlg (additivePowerIdeal K N)
    (Ideal.span {((Polynomial.X : Polynomial K) ^ N)})
    (additiveGroupCoordinateAlgEquiv K) (by
      change Ideal.span {((Polynomial.X : Polynomial K) ^ N)} =
        (Ideal.span {(additiveGroupCoordinate K) ^ N}).map
          (additiveGroupCoordinateAlgEquiv K : _ →+* Polynomial K)
      rw [Ideal.map_span]
      simp)

/-- Forward evaluation of the presentation on any quotient representative. -/
@[simp]
theorem additivePowerCoordinateAlgEquiv_mk (K : Type u) [CommRing K] (N : ℕ)
    (a : additiveGroupCoordinateRing K) :
    additivePowerCoordinateAlgEquiv K N (Ideal.Quotient.mk (additivePowerIdeal K N) a) =
      AdjoinRoot.mk ((Polynomial.X : Polynomial K) ^ N)
        (additiveGroupCoordinateAlgEquiv K a) := by
  rfl

/-- Inverse evaluation of the presentation on any polynomial representative. -/
@[simp]
theorem additivePowerCoordinateAlgEquiv_symm_mk (K : Type u) [CommRing K] (N : ℕ)
    (f : Polynomial K) :
    (additivePowerCoordinateAlgEquiv K N).symm
        (AdjoinRoot.mk ((Polynomial.X : Polynomial K) ^ N) f) =
      Ideal.Quotient.mk (additivePowerIdeal K N)
        ((additiveGroupCoordinateAlgEquiv K).symm f) := by
  rfl

/-- The quotient coordinate corresponds to the distinguished polynomial root. -/
@[simp]
theorem additivePowerCoordinateAlgEquiv_coordinate (K : Type u) [CommRing K]
    (N : ℕ) :
    additivePowerCoordinateAlgEquiv K N (additivePowerCoordinate K N) =
      AdjoinRoot.root ((Polynomial.X : Polynomial K) ^ N) := by
  simp only [additivePowerCoordinate, additivePowerCoordinateAlgEquiv_mk,
    additiveGroupCoordinateAlgEquiv_coordinate, AdjoinRoot.root]

/-- Inverse generator readback, also valid for the zero base and small powers. -/
@[simp]
theorem additivePowerCoordinateAlgEquiv_symm_root (K : Type u) [CommRing K]
    (N : ℕ) :
    (additivePowerCoordinateAlgEquiv K N).symm
      (AdjoinRoot.root ((Polynomial.X : Polynomial K) ^ N)) =
      additivePowerCoordinate K N := by
  apply (additivePowerCoordinateAlgEquiv K N).injective
  simp

/-- In a nontrivial base ring the coordinate is nonzero modulo its `N`-th
power whenever `1 < N`. -/
theorem additivePowerCoordinate_ne_zero (K : Type u) [CommRing K] [Nontrivial K]
    (N : ℕ) (hN : 1 < N) : additivePowerCoordinate K N ≠ 0 := by
  have hroot : AdjoinRoot.root ((Polynomial.X : Polynomial K) ^ N) ≠ 0 := by
    refine AdjoinRoot.mk_ne_zero_of_natDegree_lt (Polynomial.monic_X_pow N)
      Polynomial.X_ne_zero ?_
    simpa using hN
  intro hzero
  apply hroot
  simpa only [additivePowerCoordinateAlgEquiv_coordinate, map_zero] using
    congrArg (additivePowerCoordinateAlgEquiv K N) hzero

end AlgebraicGeometry
