/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import Mathlib.AlgebraicGeometry.Group.Affine
public import Mathlib.AlgebraicGeometry.Morphisms.Smooth
public import Mathlib.FieldTheory.KummerPolynomial
public import Mathlib.RingTheory.Spectrum.Prime.Topology
public import Mathlib.Topology.Connected.Clopen

/-!
# An Artin--Schreier twisted additive line

For a commutative ring `R`, a natural number `p`, and `t : R`, this file constructs the affine
scheme cut out by

`Y ^ p - Y = t * X ^ p`.

In prime characteristic `p` it is an additive group scheme.  Its defining equation has partial
derivative `-1` in the `Y` direction, so the scheme is smooth.  After scalar extension to a ring
containing a unit `p`-th root `u` of `t`, the coordinate `W = Y - uX` identifies its coordinate
ring with a polynomial ring.  Over a field of characteristic `p`, the scheme is connected for
nonzero `t`; at `t = 0` it is disconnected.

The linear `-Y` term distinguishes this equation from the Frobenius-twisted
line `Y ^ p - t * X ^ p = 0`. The latter has a nilpotent transverse
coordinate after adjoining a `p`-th root, whereas the normal form here is
a polynomial ring and requires a *unit* root. The smoothness calculation
uses the unit Jacobian entry `-1`; the zero-twist disconnection follows from
a nontrivial idempotent. No characteristic assumption is needed just to
define the equation or coordinate ring.

## Main definitions

- `ArtinSchreierTwistedLine.CoordinateRing`
- `ArtinSchreierTwistedLine.groupScheme`
- `ArtinSchreierTwistedLine.baseChangeNormalForm`

## Main results

- `ArtinSchreierTwistedLine.coordinateRing_isStandardSmooth`
- `ArtinSchreierTwistedLine.scheme_smooth`
- `ArtinSchreierTwistedLine.coordinateRing_isDomain_of_ne_zero`
- `ArtinSchreierTwistedLine.scheme_connectedSpace_of_ne_zero`
- `ArtinSchreierTwistedLine.not_scheme_connectedSpace_zero`

## References

- Mathlib, `Mathlib.Algebra.CharP.Lemmas` (the characteristic-`p` binomial
  identities used for the group law and base-change substitution).
- Mathlib, `Mathlib.RingTheory.Extension.Presentation.Submersive`,
  `Mathlib.RingTheory.Smooth.StandardSmooth`, and
  `Mathlib.AlgebraicGeometry.Morphisms.Smooth` (the Jacobian presentation,
  standard smoothness and its affine-scheme criterion).
- Mathlib, `Mathlib.RingTheory.Spectrum.Prime.Topology` and
  `Mathlib.Topology.Connected.Clopen` (idempotents, clopen subsets and the
  connectedness criterion).
- Mathlib, `Mathlib.AlgebraicGeometry.Group.Affine` (the additive Hopf
  structure's affine group scheme).
-/

public section

namespace ArtinSchreierTwistedLine

open scoped TensorProduct

noncomputable section

universe u v

variable (R : Type u) [CommRing R]

/-- The polynomial `Y ^ p - Y - t * X ^ p` in coordinates `Y = X 0`, `X = X 1`. -/
@[expose] def equation (p : ℕ) (t : R) : MvPolynomial (Fin 2) R :=
  MvPolynomial.X 0 ^ p - MvPolynomial.X 0 - MvPolynomial.C t * MvPolynomial.X 1 ^ p

/-- The ideal generated by the Artin--Schreier twisted-line equation. -/
@[expose] def equationIdeal (p : ℕ) (t : R) : Ideal (MvPolynomial (Fin 2) R) :=
  Ideal.span {equation R p t}

/-- The coordinate ring `R[X, Y] / (Y ^ p - Y - t * X ^ p)`. -/
abbrev CoordinateRing (p : ℕ) (t : R) :=
  MvPolynomial (Fin 2) R ⧸ equationIdeal R p t

/-- The `X` coordinate in the Artin--Schreier twisted-line coordinate ring. -/
@[expose] def x (p : ℕ) (t : R) : CoordinateRing R p t :=
  Ideal.Quotient.mk _ (MvPolynomial.X 1)

/-- The `Y` coordinate in the Artin--Schreier twisted-line coordinate ring. -/
@[expose] def y (p : ℕ) (t : R) : CoordinateRing R p t :=
  Ideal.Quotient.mk _ (MvPolynomial.X 0)

/-- A pair of elements satisfying `Y ^ p - Y = t * X ^ p`. -/
@[expose] def SatisfiesEquation {A : Type*} [Ring A] [Algebra R A]
    (p : ℕ) (t : R) (x y : A) : Prop :=
  y ^ p - y - algebraMap R A t * x ^ p = 0

private def eval {A : Type*} [CommRing A] [Algebra R A] (x' y' : A) :
    MvPolynomial (Fin 2) R →ₐ[R] A :=
  MvPolynomial.aeval fun i ↦ Fin.cases y' (fun _ ↦ x') i

private theorem span_equation_le_ker_eval {A : Type*} [CommRing A] [Algebra R A]
    (p : ℕ) (t : R) (x' y' : A) (h : SatisfiesEquation R p t x' y') :
    equationIdeal R p t ≤ RingHom.ker (eval R x' y').toRingHom := by
  apply Ideal.span_le.mpr
  rw [Set.singleton_subset_iff]
  apply RingHom.mem_ker.mpr
  change eval R x' y' (equation R p t) = 0
  simp only [eval, equation, map_sub, map_pow, MvPolynomial.aeval_X, map_mul,
    MvPolynomial.aeval_C, Fin.cases_zero]
  have hx1 : Fin.cases y' (fun _ : Fin 1 ↦ x') (1 : Fin 2) = x' := rfl
  rw [hx1]
  exact h

/-- The universal map out of the coordinate ring determined by a solution of its equation. -/
@[expose] def lift {A : Type*} [CommRing A] [Algebra R A] (p : ℕ) (t : R) (x' y' : A)
    (h : SatisfiesEquation R p t x' y') : CoordinateRing R p t →ₐ[R] A :=
  Ideal.Quotient.liftₐ _ (MvPolynomial.aeval fun i ↦ Fin.cases y' (fun _ ↦ x') i)
    (by
      intro _f hf
      exact RingHom.mem_ker.mp (span_equation_le_ker_eval R p t x' y' h hf))

private theorem lift_comp_mk {A : Type*} [CommRing A] [Algebra R A]
    (p : ℕ) (t : R) (x' y' : A) (h : SatisfiesEquation R p t x' y') :
    (lift R p t x' y' h).comp (Ideal.Quotient.mkₐ R (equationIdeal R p t)) =
      eval R x' y' := by
  apply Ideal.Quotient.liftₐ_comp

private theorem lift_x {A : Type*} [CommRing A] [Algebra R A]
    (p : ℕ) (t : R) (x' y' : A) (h : SatisfiesEquation R p t x' y') :
    lift R p t x' y' h (x R p t) = x' := by
  change ((lift R p t x' y' h).comp (Ideal.Quotient.mkₐ R (equationIdeal R p t)))
    (MvPolynomial.X 1) = x'
  rw [lift_comp_mk]
  simp only [eval, MvPolynomial.aeval_X]
  rfl

private theorem lift_y {A : Type*} [CommRing A] [Algebra R A]
    (p : ℕ) (t : R) (x' y' : A) (h : SatisfiesEquation R p t x' y') :
    lift R p t x' y' h (y R p t) = y' := by
  change ((lift R p t x' y' h).comp (Ideal.Quotient.mkₐ R (equationIdeal R p t)))
    (MvPolynomial.X 0) = y'
  rw [lift_comp_mk]
  simp only [eval, MvPolynomial.aeval_X, Fin.cases_zero]

/-- Algebra maps out of the coordinate ring agree if they agree on `X` and `Y`. -/
@[ext]
theorem hom_ext {A : Type*} [Semiring A] [Algebra R A]
    {p : ℕ} {t : R} {f g : CoordinateRing R p t →ₐ[R] A}
    (hx : f (x R p t) = g (x R p t)) (hy : f (y R p t) = g (y R p t)) : f = g := by
  rw [← AlgHom.cancel_right (Ideal.Quotient.mkₐ_surjective R _)]
  apply MvPolynomial.algHom_ext
  intro i
  refine Fin.cases ?_ (fun j ↦ ?_) i
  · simpa [y] using hy
  · have : j = 0 := Subsingleton.elim _ _
    subst j
    simpa [x] using hx

/-- The defining relation in the coordinate ring. -/
theorem y_pow_sub_y_eq (p : ℕ) (t : R) :
    y R p t ^ p - y R p t = algebraMap R (CoordinateRing R p t) t * x R p t ^ p := by
  rw [← sub_eq_zero]
  change Ideal.Quotient.mk _ (equation R p t) = 0
  rw [Ideal.Quotient.eq_zero_iff_mem]
  exact Ideal.subset_span (Set.mem_singleton _)

private theorem coordinate_satisfiesEquation (p : ℕ) (t : R) :
    SatisfiesEquation R p t (x R p t) (y R p t) := by
  rw [SatisfiesEquation, sub_eq_zero]
  exact y_pow_sub_y_eq R p t

private theorem satisfiesEquation_zero {A : Type*} [CommRing A] [Algebra R A]
    {p : ℕ} (hp : p ≠ 0) (t : R) : SatisfiesEquation R p t (0 : A) 0 := by
  simp [SatisfiesEquation, hp]

private theorem SatisfiesEquation.add {A : Type*} [CommRing A] [Algebra R A]
    {p : ℕ} [Fact p.Prime] [CharP A p] {t : R} {x₁ y₁ x₂ y₂ : A}
    (h₁ : SatisfiesEquation R p t x₁ y₁) (h₂ : SatisfiesEquation R p t x₂ y₂) :
    SatisfiesEquation R p t (x₁ + x₂) (y₁ + y₂) := by
  rw [SatisfiesEquation, add_pow_char, add_pow_char, sub_eq_zero]
  rw [SatisfiesEquation, sub_eq_zero] at h₁ h₂
  calc
    y₁ ^ p + y₂ ^ p - (y₁ + y₂) = (y₁ ^ p - y₁) + (y₂ ^ p - y₂) := by ring
    _ = algebraMap R A t * x₁ ^ p + algebraMap R A t * x₂ ^ p :=
      congrArg₂ (fun a b ↦ a + b) h₁ h₂
    _ = algebraMap R A t * (x₁ ^ p + x₂ ^ p) := (mul_add _ _ _).symm

private theorem SatisfiesEquation.map {A B : Type*} [CommRing A] [CommRing B]
    [Algebra R A] [Algebra R B] {p : ℕ} {t : R} {x y : A}
    (h : SatisfiesEquation R p t x y) (f : A →ₐ[R] B) :
    SatisfiesEquation R p t (f x) (f y) := by
  rw [SatisfiesEquation] at h ⊢
  rw [← map_pow, ← map_pow, ← f.commutes t, ← map_mul, ← map_sub, ← map_sub, h,
    map_zero]

private theorem SatisfiesEquation.neg {A : Type*} [CommRing A] [Algebra R A]
    {p : ℕ} [Fact p.Prime] [CharP A p] {t : R} {x y : A}
    (h : SatisfiesEquation R p t x y) : SatisfiesEquation R p t (-x) (-y) := by
  rw [SatisfiesEquation] at h ⊢
  rw [show -x = 0 - x by simp, show -y = 0 - y by simp, sub_pow_char, sub_pow_char]
  simp only [zero_pow (Fact.out : p.Prime).ne_zero, zero_sub]
  calc
    -y ^ p - -y - algebraMap R A t * -x ^ p =
        -(y ^ p - y - algebraMap R A t * x ^ p) := by ring
    _ = 0 := by rw [h, neg_zero]

private def origin {p : ℕ} [Fact p.Prime] [CharP R p] (t : R) :
    CoordinateRing R p t →ₐ[R] R :=
  lift R p t 0 0 (satisfiesEquation_zero R (Fact.out : p.Prime).ne_zero t)

private instance base_nontrivial {p : ℕ} [Fact p.Prime] [CharP R p] : Nontrivial R :=
  CharP.nontrivial_of_char_ne_one (Fact.out : p.Prime).ne_one

private instance coordinateRing_nontrivial {p : ℕ} [Fact p.Prime] [CharP R p] (t : R) :
    Nontrivial (CoordinateRing R p t) := (origin R t).domain_nontrivial

private instance coordinateRing_charP {p : ℕ} [Fact p.Prime] [CharP R p] (t : R) :
    CharP (CoordinateRing R p t) p := by
  apply charP_of_injective_algebraMap (R := R) (A := CoordinateRing R p t) _ p
  intro a b h
  have := congrArg (origin R t) h
  simpa using this

private def comulX (p : ℕ) (t : R) :
    CoordinateRing R p t ⊗[R] CoordinateRing R p t :=
  Algebra.TensorProduct.includeLeft (R := R) (S := R) (x R p t) +
    Algebra.TensorProduct.includeRight (R := R) (x R p t)

private def comulY (p : ℕ) (t : R) :
    CoordinateRing R p t ⊗[R] CoordinateRing R p t :=
  Algebra.TensorProduct.includeLeft (R := R) (S := R) (y R p t) +
    Algebra.TensorProduct.includeRight (R := R) (y R p t)

private def tensorOrigin {p : ℕ} [Fact p.Prime] [CharP R p] (t : R) :
    CoordinateRing R p t ⊗[R] CoordinateRing R p t →ₐ[R] R :=
  Algebra.TensorProduct.lift (origin R t) (origin R t) (fun _ _ ↦ Commute.all _ _)

private theorem comul_satisfiesEquation {p : ℕ} [Fact p.Prime] [CharP R p] (t : R) :
    SatisfiesEquation R p t (comulX R p t) (comulY R p t) := by
  let _ : Nontrivial (CoordinateRing R p t ⊗[R] CoordinateRing R p t) :=
    (tensorOrigin R t).domain_nontrivial
  let _ : CharP (CoordinateRing R p t ⊗[R] CoordinateRing R p t) p :=
    charP_of_injective_algebraMap (R := R)
      (A := CoordinateRing R p t ⊗[R] CoordinateRing R p t)
      (by
        intro a b h
        have := congrArg (tensorOrigin R t) h
        simpa [tensorOrigin] using this) p
  rw [comulX, comulY]
  have hleft := SatisfiesEquation.map (R := R)
    (A := CoordinateRing R p t)
    (B := CoordinateRing R p t ⊗[R] CoordinateRing R p t)
    (coordinate_satisfiesEquation R p t)
    (Algebra.TensorProduct.includeLeft (R := R) (S := R))
  have hright := SatisfiesEquation.map (R := R)
    (A := CoordinateRing R p t)
    (B := CoordinateRing R p t ⊗[R] CoordinateRing R p t)
    (coordinate_satisfiesEquation R p t)
    (Algebra.TensorProduct.includeRight (R := R))
  exact SatisfiesEquation.add (R := R) hleft hright

/-- Comultiplication corresponding to coordinatewise addition. -/
@[expose] def comul {p : ℕ} [Fact p.Prime] [CharP R p] (t : R) :
    CoordinateRing R p t →ₐ[R] CoordinateRing R p t ⊗[R] CoordinateRing R p t :=
  lift R p t
    (Algebra.TensorProduct.includeLeft (R := R) (S := R) (x R p t) +
      Algebra.TensorProduct.includeRight (R := R) (x R p t))
    (Algebra.TensorProduct.includeLeft (R := R) (S := R) (y R p t) +
      Algebra.TensorProduct.includeRight (R := R) (y R p t))
    (by exact comul_satisfiesEquation R t)

private theorem comul_x {p : ℕ} [Fact p.Prime] [CharP R p] (t : R) :
    comul R t (x R p t) = comulX R p t := lift_x R _ _ _ _ _

private theorem comul_y {p : ℕ} [Fact p.Prime] [CharP R p] (t : R) :
    comul R t (y R p t) = comulY R p t := lift_y R _ _ _ _ _

/-- Counit corresponding to the origin. -/
@[expose] def counit {p : ℕ} [Fact p.Prime] [CharP R p]
    (t : R) : CoordinateRing R p t →ₐ[R] R :=
  lift R p t 0 0 (by exact satisfiesEquation_zero R (Fact.out : p.Prime).ne_zero t)

private theorem counit_x {p : ℕ} [Fact p.Prime] [CharP R p] (t : R) :
    counit R t (x R p t) = 0 := by simp [counit, lift_x]

private theorem counit_y {p : ℕ} [Fact p.Prime] [CharP R p] (t : R) :
    counit R t (y R p t) = 0 := by simp [counit, lift_y]

/-- Antipode corresponding to coordinatewise negation. -/
@[expose] def antipode {p : ℕ} [Fact p.Prime] [CharP R p] (t : R) :
    CoordinateRing R p t →ₐ[R] CoordinateRing R p t :=
  lift R p t (-x R p t) (-y R p t)
    (by exact (coordinate_satisfiesEquation R p t).neg)

private theorem antipode_x {p : ℕ} [Fact p.Prime] [CharP R p] (t : R) :
    antipode R t (x R p t) = -x R p t := lift_x R _ _ _ _ _

private theorem antipode_y {p : ℕ} [Fact p.Prime] [CharP R p] (t : R) :
    antipode R t (y R p t) = -y R p t := lift_y R _ _ _ _ _

/-- The bialgebra structure dual to coordinatewise addition. -/
noncomputable instance coordinateRing_bialgebra {p : ℕ} [Fact p.Prime] [CharP R p]
    (t : R) : Bialgebra R (CoordinateRing R p t) :=
  Bialgebra.ofAlgHom (comul R t) (counit R t)
    (by
      apply hom_ext
      · simp [comul_x, comulX, TensorProduct.add_tmul, TensorProduct.tmul_add,
          Algebra.TensorProduct.one_def, add_assoc]
      · simp [comul_y, comulY, TensorProduct.add_tmul, TensorProduct.tmul_add,
          Algebra.TensorProduct.one_def, add_assoc])
    (by
      apply hom_ext <;>
        simp [comul_x, comul_y, comulX, comulY, counit_x, counit_y])
    (by
      apply hom_ext <;>
        simp [comul_x, comul_y, comulX, comulY, counit_x, counit_y])

/-- The Hopf-algebra structure dual to coordinatewise addition and negation. -/
noncomputable instance coordinateRing_hopfAlgebra {p : ℕ} [Fact p.Prime] [CharP R p]
    (t : R) : HopfAlgebra R (CoordinateRing R p t) :=
  HopfAlgebra.ofAlgHom (antipode R t)
    (by
      apply hom_ext
      · change (Algebra.TensorProduct.lift (antipode R t)
          (AlgHom.id R (CoordinateRing R p t)) (fun _ _ ↦ Commute.all _ _))
            (comul R t (x R p t)) = algebraMap R _ (counit R t (x R p t))
        simp [comul_x, comulX, antipode_x, counit_x]
      · change (Algebra.TensorProduct.lift (antipode R t)
          (AlgHom.id R (CoordinateRing R p t)) (fun _ _ ↦ Commute.all _ _))
            (comul R t (y R p t)) = algebraMap R _ (counit R t (y R p t))
        simp [comul_y, comulY, antipode_y, counit_y])
    (by
      apply hom_ext
      · change (Algebra.TensorProduct.lift (AlgHom.id R (CoordinateRing R p t))
          (antipode R t) (fun _ _ ↦ Commute.all _ _))
            (comul R t (x R p t)) = algebraMap R _ (counit R t (x R p t))
        simp [comul_x, comulX, antipode_x, counit_x]
      · change (Algebra.TensorProduct.lift (AlgHom.id R (CoordinateRing R p t))
          (antipode R t) (fun _ _ ↦ Commute.all _ _))
            (comul R t (y R p t)) = algebraMap R _ (counit R t (y R p t))
        simp [comul_y, comulY, antipode_y, counit_y])

open CategoryTheory AlgebraicGeometry

/-- The affine scheme over `R` represented by the Artin--Schreier coordinate ring. -/
abbrev scheme (p : ℕ) (t : R) : Over (Spec (.of R)) :=
  (Spec (.of (CoordinateRing R p t))).asOver (Spec (.of R))

/-- The additive group scheme defined by `Y ^ p - Y = t * X ^ p`, distinct
from the Frobenius-twisted equation `Y ^ p = t * X ^ p`. -/
abbrev groupScheme {p : ℕ} [Fact p.Prime] [CharP R p] (t : R) :
    Grp (Over (Spec (.of R))) :=
  ⟨scheme R p t⟩

/-! ### Smoothness -/

private def relationFamily (p : ℕ) (t : R) : Unit → MvPolynomial (Fin 2) R :=
  fun _ ↦ equation R p t

private def relationVariable : Unit → Fin 2 := fun _ ↦ 0

private theorem relationVariable_injective :
    Function.Injective (relationVariable : Unit → Fin 2) :=
  fun _ _ _ ↦ Subsingleton.elim _ _

private theorem span_range_relationFamily (p : ℕ) (t : R) :
    Ideal.span (Set.range (relationFamily R p t)) = equationIdeal R p t := by
  simp [relationFamily, equationIdeal, Set.range_unique]

private noncomputable def preSubmersivePresentation (p : ℕ) (t : R) :
    Algebra.PreSubmersivePresentation R (CoordinateRing R p t) (Fin 2) Unit := by
  let P := Algebra.PreSubmersivePresentation.naive
    (v := relationFamily R p t) relationVariable relationVariable_injective
  exact P.ofAlgEquiv (Ideal.quotientEquivAlgOfEq R (span_range_relationFamily R p t))

private theorem preSubmersivePresentation_jacobiMatrix [CharP R p] (t : R) :
    (preSubmersivePresentation R p t).jacobiMatrix =
      Matrix.of (fun _ _ : Unit ↦ (-1 : MvPolynomial (Fin 2) R)) := by
  ext i j
  simp [preSubmersivePresentation, Algebra.PreSubmersivePresentation.jacobiMatrix_ofAlgEquiv,
    Algebra.PreSubmersivePresentation.jacobiMatrix_naive, relationFamily, relationVariable,
    equation]

private noncomputable def submersivePresentation [CharP R p] (t : R) :
    Algebra.SubmersivePresentation R (CoordinateRing R p t) (Fin 2) Unit where
  toPreSubmersivePresentation := preSubmersivePresentation R p t
  jacobian_isUnit := by
    rw [Algebra.PreSubmersivePresentation.jacobian_eq_jacobiMatrix_det,
      preSubmersivePresentation_jacobiMatrix]
    rw [Matrix.det_unique]
    exact isUnit_neg_one.map (algebraMap _ _)

/-- The coordinate ring is standard smooth over the base ring. -/
theorem coordinateRing_isStandardSmooth [CharP R p] (t : R) :
    Algebra.IsStandardSmooth R (CoordinateRing R p t) :=
  (submersivePresentation R t).isStandardSmooth

/-- The coordinate ring is smooth over the base ring. -/
theorem coordinateRing_smooth [CharP R p] (t : R) :
    Algebra.Smooth R (CoordinateRing R p t) := by
  let _ : Algebra.IsStandardSmooth R (CoordinateRing R p t) :=
    coordinateRing_isStandardSmooth R t
  infer_instance

/-- The structure morphism is smooth: the defining relation has partial
derivative `-1` with respect to `Y`. -/
theorem scheme_smooth [CharP R p] (t : R) : Smooth (scheme R p t).hom := by
  change Smooth (Spec.map (CommRingCat.ofHom (algebraMap R (CoordinateRing R p t))))
  rw [HasRingHomProperty.Spec_iff (P := @Smooth)]
  simpa only [CommRingCat.hom_ofHom] using
    (RingHom.smooth_algebraMap.mpr (coordinateRing_smooth R t))

/-! ### Scalar-extension normal form -/

variable (L : Type v) [CommRing L] [Algebra R L]

/-- The root coordinate `W = 1 ⊗ Y - u ⊗ X` after scalar extension. -/
@[expose] def W (p : ℕ) (t : R) (u : Lˣ) : L ⊗[R] CoordinateRing R p t :=
  (1 : L) ⊗ₜ[R] y R p t - (u : L) ⊗ₜ[R] x R p t

private theorem normalFormCoordinates_satisfyEquation {p : ℕ} [Fact p.Prime] [CharP L p]
    (t : R) (u : Lˣ) (hu : (u : L) ^ p = algebraMap R L t) :
    SatisfiesEquation R p t
      (Polynomial.C ((u⁻¹ : Lˣ) : L) * (Polynomial.X ^ p - Polynomial.X))
      (Polynomial.X ^ p) := by
  have hcoef : algebraMap R L t * (((u⁻¹ : Lˣ) : L) ^ p) = 1 := by
    rw [← hu, ← mul_pow]
    simp
  rw [SatisfiesEquation,
    mul_pow (Polynomial.C ((u⁻¹ : Lˣ) : L)) (Polynomial.X ^ p - Polynomial.X) p,
    sub_pow_char (Polynomial.X ^ p) Polynomial.X, ← Polynomial.C_pow]
  change (Polynomial.X ^ p) ^ p - Polynomial.X ^ p -
      Polynomial.C (algebraMap R L t) *
        (Polynomial.C (((u⁻¹ : Lˣ) : L) ^ p) *
          ((Polynomial.X ^ p) ^ p - Polynomial.X ^ p)) = 0
  rw [← mul_assoc, ← Polynomial.C_mul, hcoef]
  simp

private def normalFormHom {p : ℕ} [Fact p.Prime] [CharP L p]
    (t : R) (u : Lˣ) (hu : (u : L) ^ p = algebraMap R L t) :
    L ⊗[R] CoordinateRing R p t →ₐ[L] Polynomial L :=
  (lift R p t
    (Polynomial.C ((u⁻¹ : Lˣ) : L) * (Polynomial.X ^ p - Polynomial.X))
    (Polynomial.X ^ p) (normalFormCoordinates_satisfyEquation R L t u hu)).liftEquiv
      R L (CoordinateRing R p t) (Polynomial L)

private theorem normalFormHom_tmul_x {p : ℕ} [Fact p.Prime] [CharP L p]
    (t : R) (u : Lˣ) (hu : (u : L) ^ p = algebraMap R L t) :
    normalFormHom R L t u hu ((1 : L) ⊗ₜ[R] x R p t) =
      Polynomial.C ((u⁻¹ : Lˣ) : L) * (Polynomial.X ^ p - Polynomial.X) := by
  simp [normalFormHom, lift_x]

private theorem normalFormHom_tmul_y {p : ℕ} [Fact p.Prime] [CharP L p]
    (t : R) (u : Lˣ) (hu : (u : L) ^ p = algebraMap R L t) :
    normalFormHom R L t u hu ((1 : L) ⊗ₜ[R] y R p t) = Polynomial.X ^ p := by
  simp [normalFormHom, lift_y]

private theorem normalFormHom_W {p : ℕ} [Fact p.Prime] [CharP L p]
    (t : R) (u : Lˣ) (hu : (u : L) ^ p = algebraMap R L t) :
    normalFormHom R L t u hu (W R L p t u) = Polynomial.X := by
  rw [W, map_sub, normalFormHom_tmul_y]
  rw [TensorProduct.tmul_eq_smul_one_tmul]
  rw [map_smul, normalFormHom_tmul_x]
  rw [Algebra.smul_def]
  change Polynomial.X ^ p - Polynomial.C (u : L) *
      (Polynomial.C ((u⁻¹ : Lˣ) : L) * (Polynomial.X ^ p - Polynomial.X)) = Polynomial.X
  rw [← mul_assoc, ← Polynomial.C_mul]
  rw [Units.mul_inv, Polynomial.C_1]
  ring

private def normalFormInv {p : ℕ} [Fact p.Prime] [CharP L p]
    (t : R) (u : Lˣ) : Polynomial L →ₐ[L] L ⊗[R] CoordinateRing R p t :=
  Polynomial.aeval (W R L p t u)

private theorem normalFormInv_X {p : ℕ} [Fact p.Prime] [CharP L p]
    (t : R) (u : Lˣ) : normalFormInv R L t u Polynomial.X = W R L p t u := by
  exact Polynomial.aeval_X _

private theorem W_pow {p : ℕ} [Fact p.Prime] [CharP L p]
    (t : R) (u : Lˣ) (hu : (u : L) ^ p = algebraMap R L t) :
    W R L p t u ^ p = (1 : L) ⊗ₜ[R] y R p t := by
  let _ : Nontrivial (L ⊗[R] CoordinateRing R p t) :=
    (normalFormHom R L t u hu).domain_nontrivial
  let _ : CharP (L ⊗[R] CoordinateRing R p t) p :=
    charP_of_injective_algebraMap (R := L) (A := L ⊗[R] CoordinateRing R p t)
      (by
        intro a b h
        have := congrArg (normalFormHom R L t u hu) h
        have hab : algebraMap L (Polynomial L) a = algebraMap L (Polynomial L) b := by
          simpa only [AlgHom.commutes] using this
        exact Polynomial.C_injective hab) p
  rw [W,
    sub_pow_char ((1 : L) ⊗ₜ[R] y R p t) ((u : L) ⊗ₜ[R] x R p t)]
  simp only [Algebra.TensorProduct.tmul_pow, one_pow]
  rw [hu]
  change (1 : L) ⊗ₜ[R] (y R p t ^ p) -
      algebraMap R L t ⊗ₜ[R] (x R p t ^ p) = (1 : L) ⊗ₜ[R] y R p t
  calc
    ((1 : L) ⊗ₜ[R] (y R p t ^ p)) -
        (algebraMap R L t ⊗ₜ[R] (x R p t ^ p)) =
        (1 : L) ⊗ₜ[R] (y R p t ^ p - y R p t) +
          (1 : L) ⊗ₜ[R] y R p t -
            (algebraMap R L t) ⊗ₜ[R] (x R p t ^ p) := by
      simp [TensorProduct.tmul_sub]
    _ = (1 : L) ⊗ₜ[R] y R p t := by
      rw [y_pow_sub_y_eq]
      rw [show algebraMap R (CoordinateRing R p t) t * x R p t ^ p =
        t • (x R p t ^ p) from
          (Algebra.smul_def (R := R) t (x R p t ^ p)).symm]
      rw [TensorProduct.tmul_smul]
      rw [TensorProduct.smul_tmul']
      rw [Algebra.smul_def (R := R) t (1 : L), mul_one]
      abel

private theorem W_pow_sub_W {p : ℕ} [Fact p.Prime] [CharP L p]
    (t : R) (u : Lˣ) (hu : (u : L) ^ p = algebraMap R L t) :
    W R L p t u ^ p - W R L p t u = (u : L) ⊗ₜ[R] x R p t := by
  rw [W_pow R L t u hu, W]
  abel

private theorem normalFormInv_comp_hom {p : ℕ} [Fact p.Prime] [CharP L p]
    (t : R) (u : Lˣ) (hu : (u : L) ^ p = algebraMap R L t) :
    (normalFormInv R L t u).comp (normalFormHom R L t u hu) =
      AlgHom.id L (L ⊗[R] CoordinateRing R p t) := by
  apply Algebra.TensorProduct.ext_ring
  apply hom_ext
  · change normalFormInv R L t u
        (normalFormHom R L t u hu ((1 : L) ⊗ₜ[R] x R p t)) =
      (1 : L) ⊗ₜ[R] x R p t
    rw [normalFormHom_tmul_x]
    rw [map_mul, map_sub]
    have hpow : normalFormInv R L t u (Polynomial.X ^ p) =
        (normalFormInv R L t u Polynomial.X) ^ p :=
      map_pow (normalFormInv R L t u).toRingHom Polynomial.X p
    rw [hpow]
    rw [normalFormInv_X]
    rw [W_pow_sub_W R L t u hu]
    rw [show normalFormInv R L t u (Polynomial.C ((u⁻¹ : Lˣ) : L)) =
      algebraMap L (L ⊗[R] CoordinateRing R p t) ((u⁻¹ : Lˣ) : L) from
        (normalFormInv R L t u).commutes _]
    simp [Algebra.TensorProduct.tmul_mul_tmul]
  · change normalFormInv R L t u
        (normalFormHom R L t u hu ((1 : L) ⊗ₜ[R] y R p t)) =
      (1 : L) ⊗ₜ[R] y R p t
    rw [normalFormHom_tmul_y]
    have hpow : normalFormInv R L t u (Polynomial.X ^ p) =
        (normalFormInv R L t u Polynomial.X) ^ p :=
      map_pow (normalFormInv R L t u).toRingHom Polynomial.X p
    rw [hpow]
    rw [normalFormInv_X, W_pow R L t u hu]

private theorem normalFormHom_comp_inv {p : ℕ} [Fact p.Prime] [CharP L p]
    (t : R) (u : Lˣ) (hu : (u : L) ^ p = algebraMap R L t) :
    (normalFormHom R L t u hu).comp (normalFormInv R L t u) =
      AlgHom.id L (Polynomial L) := by
  ext
  simp [normalFormInv_X, normalFormHom_W R L t u hu]

/-- After choosing a *unit* root `u` with `u ^ p = t`, scalar extension
identifies the Artin--Schreier twisted line with the affine line having
coordinate `W = Y - uX`; the inverse coordinate formula uses `u⁻¹`. -/
@[expose] def baseChangeNormalForm {p : ℕ} [Fact p.Prime] [CharP L p]
    (t : R) (u : Lˣ) (hu : (u : L) ^ p = algebraMap R L t) :
    L ⊗[R] CoordinateRing R p t ≃ₐ[L] Polynomial L :=
  AlgEquiv.ofAlgHom
    ((lift R p t
      (Polynomial.C ((u⁻¹ : Lˣ) : L) * (Polynomial.X ^ p - Polynomial.X))
      (Polynomial.X ^ p)
      (by exact normalFormCoordinates_satisfyEquation R L t u hu)).liftEquiv
        R L (CoordinateRing R p t) (Polynomial L))
    (Polynomial.aeval (W R L p t u))
    (by exact normalFormHom_comp_inv R L t u hu)
    (by exact normalFormInv_comp_hom R L t u hu)

@[simp]
theorem baseChangeNormalForm_tmul_x {p : ℕ} [Fact p.Prime] [CharP L p]
    (t : R) (u : Lˣ) (hu : (u : L) ^ p = algebraMap R L t) :
    baseChangeNormalForm R L t u hu ((1 : L) ⊗ₜ[R] x R p t) =
      Polynomial.C ((u⁻¹ : Lˣ) : L) * (Polynomial.X ^ p - Polynomial.X) := by
  exact normalFormHom_tmul_x R L t u hu

@[simp]
theorem baseChangeNormalForm_tmul_y {p : ℕ} [Fact p.Prime] [CharP L p]
    (t : R) (u : Lˣ) (hu : (u : L) ^ p = algebraMap R L t) :
    baseChangeNormalForm R L t u hu ((1 : L) ⊗ₜ[R] y R p t) = Polynomial.X ^ p := by
  exact normalFormHom_tmul_y R L t u hu

@[simp]
theorem baseChangeNormalForm_W {p : ℕ} [Fact p.Prime] [CharP L p]
    (t : R) (u : Lˣ) (hu : (u : L) ^ p = algebraMap R L t) :
    baseChangeNormalForm R L t u hu (W R L p t u) = Polynomial.X := by
  exact normalFormHom_W R L t u hu

@[simp]
theorem baseChangeNormalForm_symm_X {p : ℕ} [Fact p.Prime] [CharP L p]
    (t : R) (u : Lˣ) (hu : (u : L) ^ p = algebraMap R L t) :
    (baseChangeNormalForm R L t u hu).symm Polynomial.X = W R L p t u := by
  exact normalFormInv_X R L t u

/-! ### Connectedness -/

/-- A unit-root base change has connected spectrum. -/
theorem baseChangeSpec_connectedSpace [IsDomain L] {p : ℕ} [Fact p.Prime] [CharP L p]
    (t : R) (u : Lˣ) (hu : (u : L) ^ p = algebraMap R L t) :
    ConnectedSpace (Spec (.of (L ⊗[R] CoordinateRing R p t))) := by
  let _ : IsDomain (L ⊗[R] CoordinateRing R p t) :=
    (baseChangeNormalForm R L t u hu).injective.isDomain
      (baseChangeNormalForm R L t u hu).toRingEquiv.toRingHom
  infer_instance

/-- Over a field, a nonzero twist has an integral-domain coordinate ring. -/
theorem coordinateRing_isDomain_of_ne_zero
    (K : Type u) [Field K] {p : ℕ} (hp : p.Prime) [CharP K p]
    {t : K} (ht : t ≠ 0) : IsDomain (CoordinateRing K p t) := by
  let _ : Fact p.Prime := ⟨hp⟩
  let α : AlgebraicClosure K := Classical.choose
    (IsAlgClosed.exists_pow_nat_eq (algebraMap K (AlgebraicClosure K) t) hp.pos)
  have hα : α ^ p = algebraMap K (AlgebraicClosure K) t := Classical.choose_spec
    (IsAlgClosed.exists_pow_nat_eq (algebraMap K (AlgebraicClosure K) t) hp.pos)
  have hα0 : α ≠ 0 := by
    intro h
    rw [h, zero_pow hp.ne_zero] at hα
    apply ht
    apply (algebraMap K (AlgebraicClosure K)).injective
    rw [map_zero]
    exact hα.symm
  let u : (AlgebraicClosure K)ˣ := Units.mk0 α hα0
  have hu : (u : AlgebraicClosure K) ^ p = algebraMap K (AlgebraicClosure K) t := hα
  let _ : CharP (AlgebraicClosure K) p :=
    CharP.of_ringHom_of_ne_zero (algebraMap K (AlgebraicClosure K)) p hp.ne_zero
  let _ : IsDomain ((AlgebraicClosure K) ⊗[K] CoordinateRing K p t) :=
    (baseChangeNormalForm K (AlgebraicClosure K) t u hu).injective.isDomain
      (baseChangeNormalForm K (AlgebraicClosure K) t u hu).toRingEquiv.toRingHom
  exact (Algebra.TensorProduct.includeRight_injective
    (R := K) (A := AlgebraicClosure K) (B := CoordinateRing K p t)
    (algebraMap K (AlgebraicClosure K)).injective).isDomain
      (Algebra.TensorProduct.includeRight : CoordinateRing K p t →ₐ[K]
        (AlgebraicClosure K) ⊗[K] CoordinateRing K p t)

/-- Over a field, a nonzero twist has connected underlying affine scheme. -/
theorem scheme_connectedSpace_of_ne_zero
    (K : Type u) [Field K] {p : ℕ} (hp : p.Prime) [CharP K p]
    {t : K} (ht : t ≠ 0) : ConnectedSpace (scheme K p t).left := by
  let _ : IsDomain (CoordinateRing K p t) := coordinateRing_isDomain_of_ne_zero K hp ht
  change ConnectedSpace (PrimeSpectrum (CoordinateRing K p t))
  infer_instance

private def zeroPoint (K : Type u) [Field K] {p : ℕ} (hp : p.Prime) [CharP K p]
    (a : K) (ha : a ^ p - a = 0) : CoordinateRing K p 0 →ₐ[K] K :=
  lift K p 0 0 a (by simpa [SatisfiesEquation, hp.ne_zero] using ha)

private theorem zero_idempotent {K : Type u} [Field K] {p : ℕ} (hp : p.Prime)
    [CharP K p] : IsIdempotentElem (y K p 0 ^ (p - 1)) := by
  have hy : y K p 0 ^ p = y K p 0 := by
    exact sub_eq_zero.mp (by simpa using y_pow_sub_y_eq K p 0)
  have hp2 : 2 ≤ p := hp.two_le
  rw [isIdempotentElem_iff]
  calc
    y K p 0 ^ (p - 1) * y K p 0 ^ (p - 1) =
        y K p 0 ^ ((p - 1) + (p - 1)) := (pow_add _ _ _).symm
    _ = y K p 0 ^ (p + (p - 2)) := by congr 1; omega
    _ = y K p 0 ^ p * y K p 0 ^ (p - 2) := pow_add _ _ _
    _ = y K p 0 * y K p 0 ^ (p - 2) := by rw [hy]
    _ = y K p 0 ^ ((p - 2) + 1) := by rw [mul_comm, pow_succ]
    _ = y K p 0 ^ (p - 1) := by congr 1; omega

private theorem zero_idempotent_ne_zero {K : Type u} [Field K] {p : ℕ} (hp : p.Prime)
    [CharP K p] : y K p 0 ^ (p - 1) ≠ 0 := by
  intro h
  have hmap := congrArg (zeroPoint K hp 1 (by simp)) h
  have hy : zeroPoint K hp 1 (by simp) (y K p 0) = 1 := by
    exact lift_y K p 0 0 1 _
  rw [map_pow, hy, one_pow, map_zero] at hmap
  exact one_ne_zero hmap

private theorem zero_idempotent_ne_one {K : Type u} [Field K] {p : ℕ} (hp : p.Prime)
    [CharP K p] : y K p 0 ^ (p - 1) ≠ 1 := by
  intro h
  have hmap := congrArg (zeroPoint K hp 0 (by simp [hp.ne_zero])) h
  have hpm1 : p - 1 ≠ 0 := (Nat.sub_pos_of_lt hp.one_lt).ne'
  have hy : zeroPoint K hp 0 (by simp [hp.ne_zero]) (y K p 0) = 0 := by
    exact lift_y K p 0 0 0 _
  rw [map_pow, hy, zero_pow hpm1, map_one] at hmap
  exact zero_ne_one hmap

/-- At zero twist, the Artin--Schreier scheme is disconnected. -/
theorem not_scheme_connectedSpace_zero
    (K : Type u) [Field K] {p : ℕ} (hp : p.Prime) [CharP K p] :
    ¬ ConnectedSpace (scheme K p 0).left := by
  change ¬ ConnectedSpace (PrimeSpectrum (CoordinateRing K p 0))
  intro h
  let e : {z : CoordinateRing K p 0 // IsIdempotentElem z} :=
    ⟨y K p 0 ^ (p - 1), zero_idempotent hp⟩
  let E := PrimeSpectrum.isIdempotentElemEquivClopens
    (R := CoordinateRing K p 0)
  let s : TopologicalSpace.Clopens (PrimeSpectrum (CoordinateRing K p 0)) :=
    E e
  rcases (connectedSpace_iff_clopen.mp h).2 (s : Set _) s.2 with hs | hs
  · have hs' : s = ⊥ := SetLike.ext' hs
    have he0 : e = E.symm ⊥ := by
      calc
        e = E.symm (E e) := (E.symm_apply_apply e).symm
        _ = E.symm s := rfl
        _ = E.symm ⊥ := congrArg E.symm hs'
    have hval := congrArg Subtype.val he0
    rw [PrimeSpectrum.isIdempotentElemEquivClopens_symm_bot] at hval
    exact zero_idempotent_ne_zero hp hval
  · have hs' : s = ⊤ := SetLike.ext' hs
    have he1 : e = E.symm ⊤ := by
      calc
        e = E.symm (E e) := (E.symm_apply_apply e).symm
        _ = E.symm s := rfl
        _ = E.symm ⊤ := congrArg E.symm hs'
    have hval := congrArg Subtype.val he1
    rw [PrimeSpectrum.isIdempotentElemEquivClopens_symm_top] at hval
    exact zero_idempotent_ne_one hp hval

end

end ArtinSchreierTwistedLine
