/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import AlgebraicGroups.GroupTheory.Diagonal
public import AlgebraicGroups.Algebra.GeneralLinearCoordinateRing
public import Mathlib.RingTheory.HopfAlgebra.Quotient

/-! # The diagonal Hopf quotient of the general linear coordinate ring -/

@[expose] public section

noncomputable section

open GeneralLinearCoordinateRing
open scoped TensorProduct

universe u

namespace DiagonalCoordinateRing

variable (K : Type u) [CommRing K] (ι : Type u) [Fintype ι] [DecidableEq ι]

/-- The off-diagonal relation on the actual localized GL coordinate ring. -/
def relation (i j : ι) : GeneralLinearCoordinateRing.CoordinateRing K ι :=
  if i = j then 0 else matrix K ι i j

/-- The ideal generated by all off-diagonal entries of the universal GL matrix. -/
def ideal : Ideal (GeneralLinearCoordinateRing.CoordinateRing K ι) :=
  Ideal.span (Set.range fun p : ι × ι => relation K ι p.1 p.2)

/-- The coordinate ring of the closed diagonal subgroup of GL. -/
abbrev CoordinateRing := GeneralLinearCoordinateRing.CoordinateRing K ι ⧸ ideal K ι

/-- Quotient of the published GL coordinate ring. -/
def quotient : GeneralLinearCoordinateRing.CoordinateRing K ι →ₐ[K] CoordinateRing K ι :=
  Ideal.Quotient.mkₐ K (ideal K ι)

theorem relation_mem (i j : ι) : relation K ι i j ∈ ideal K ι :=
  Ideal.subset_span ⟨(i, j), rfl⟩

@[simp] theorem quotient_offDiagonal (i j : ι) (h : i ≠ j) :
    quotient K ι (matrix K ι i j) = 0 := by
  have hz : quotient K ι (relation K ι i j) = 0 :=
    Ideal.Quotient.eq_zero_iff_mem.mpr (relation_mem K ι i j)
  simpa [relation, h] using hz

/-- The universal invertible diagonal matrix in the quotient coordinate ring. -/
def universal : Matrix.DiagonalGroup ι (CoordinateRing K ι) :=
  ⟨Matrix.GeneralLinearGroup.map (quotient K ι).toRingHom
    (GeneralLinearCoordinateRing.universal K ι), by
    intro i j hij
    change quotient K ι (matrix K ι i j) = 0
    exact quotient_offDiagonal K ι i j hij⟩

@[simp] theorem universal_apply (i j : ι) :
    (universal K ι).1 i j = quotient K ι (matrix K ι i j) := rfl

theorem universal_diagUnit (i : ι) :
    IsUnit (quotient K ι (matrix K ι i i)) :=
  Matrix.DiagonalGroup.isUnit_entry (universal K ι) i

theorem universal_detInverse :
    quotient K ι (detInverse K ι) *
      (∏ i, quotient K ι (matrix K ι i i)) = 1 := by
  have hm := congrArg (quotient K ι) (det_mul_detInverse K ι)
  rw [map_mul, map_one, AlgHom.map_det] at hm
  have hdiag : ((universal K ι).1 : Matrix ι ι (CoordinateRing K ι)) =
      Matrix.diagonal (fun i => quotient K ι (matrix K ι i i)) := by
    ext i j
    by_cases hij : i = j
    · subst j
      simp [universal_apply]
    · simpa only [universal_apply, Matrix.diagonal_apply_ne _ hij] using
        quotient_offDiagonal K ι i j hij
  change ((universal K ι).1 : Matrix ι ι (CoordinateRing K ι)).det *
    quotient K ι (detInverse K ι) = 1 at hm
  rw [hdiag, Matrix.det_diagonal] at hm
  rwa [mul_comm] at hm

set_option linter.style.haveILetI false in
/-- The defining ideal is stable under counit, coproduct and antipode. -/
theorem ideal_isHopfIdeal_proof : (ideal K ι).IsHopfIdeal K := by
  let q := quotient K ι
  let comulQuotient : GeneralLinearCoordinateRing.CoordinateRing K ι →ₐ[K]
      CoordinateRing K ι ⊗[K] CoordinateRing K ι :=
    (Algebra.TensorProduct.map q q).comp
      (Bialgebra.comulAlgHom K (GeneralLinearCoordinateRing.CoordinateRing K ι))
  letI : CommRing (CoordinateRing K ι ⊗[K] CoordinateRing K ι) := inferInstance
  have counit_gen (i j : ι) :
      (Bialgebra.counitAlgHom K (GeneralLinearCoordinateRing.CoordinateRing K ι))
        (relation K ι i j) = 0 := by
    by_cases hij : i = j
    · simp [relation, hij]
    · simp only [relation, hij, ite_false]
      change Coalgebra.counit (R := K) (matrix K ι i j) = 0
      rw [native_counit_matrix]
      simp [hij]
  have comul_gen (i j : ι) : comulQuotient (relation K ι i j) = 0 := by
    by_cases hij : i = j
    · simp [relation, hij]
    · simp only [relation, hij, ite_false]
      change (Algebra.TensorProduct.map q q)
        (Coalgebra.comul (R := K) (matrix K ι i j)) = 0
      rw [native_comul_matrix, map_sum]
      apply Finset.sum_eq_zero
      intro index _
      rw [Algebra.TensorProduct.map_tmul]
      by_cases hik : i = index
      · subst index
        rw [quotient_offDiagonal K ι i j hij, TensorProduct.tmul_zero]
      · rw [quotient_offDiagonal K ι i index hik, TensorProduct.zero_tmul]
  have antipode_gen (i j : ι) :
      HopfAlgebra.antipode K (relation K ι i j) ∈ ideal K ι := by
    apply Ideal.Quotient.eq_zero_iff_mem.mp
    by_cases hij : i = j
    · simp [relation, hij]
    · simp only [relation, hij, ite_false]
      change q (HopfAlgebra.antipode K (matrix K ι i j)) = 0
      have hinv := ((Matrix.GeneralLinearGroup.map q.toRingHom).map_inv
        (GeneralLinearCoordinateRing.universal K ι)).symm
      have hantipode : q (HopfAlgebra.antipode K (matrix K ι i j)) =
          ((universal K ι).1⁻¹ : Matrix.GeneralLinearGroup ι (CoordinateRing K ι)) i j := by
        rw [native_antipode_matrix]
        have heq := congrArg
          (fun g : Matrix.GeneralLinearGroup ι (CoordinateRing K ι) =>
            (g : Matrix ι ι (CoordinateRing K ι)) i j) hinv
        exact heq.symm
      rw [hantipode]
      exact (Matrix.diagonalSubgroup ι (CoordinateRing K ι)).inv_mem
        (universal K ι).2 i j hij
  refine { counit_eq_zero := ?_, map_mkQ_comul_eq_zero := ?_, antipode_mem := ?_ }
  · intro x hx
    have h : ideal K ι ≤ RingHom.ker
        (Bialgebra.counitAlgHom K
          (GeneralLinearCoordinateRing.CoordinateRing K ι)).toRingHom := by
      apply Ideal.span_le.mpr
      rintro _ ⟨⟨i, j⟩, rfl⟩
      exact RingHom.mem_ker.mpr (counit_gen i j)
    change (Bialgebra.counitAlgHom K
      (GeneralLinearCoordinateRing.CoordinateRing K ι)) x = 0
    exact RingHom.mem_ker.mp (h hx)
  · intro x hx
    have h : ideal K ι ≤ RingHom.ker comulQuotient.toRingHom := by
      apply Ideal.span_le.mpr
      rintro _ ⟨⟨i, j⟩, rfl⟩
      exact RingHom.mem_ker.mpr (comul_gen i j)
    exact RingHom.mem_ker.mp (h hx)
  · intro x hx
    have h : ideal K ι ≤ (ideal K ι).comap
        (HopfAlgebra.antipodeAlgHom K
          (GeneralLinearCoordinateRing.CoordinateRing K ι)).toRingHom := by
      apply Ideal.span_le.mpr
      rintro _ ⟨⟨i, j⟩, rfl⟩
      exact antipode_gen i j
    exact h hx

instance ideal_isHopfIdeal : (ideal K ι).IsHopfIdeal K :=
  ideal_isHopfIdeal_proof K ι

instance finiteType : Algebra.FiniteType K (CoordinateRing K ι) :=
  Algebra.FiniteType.of_surjective (quotient K ι) Ideal.Quotient.mk_surjective

end DiagonalCoordinateRing
