/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import Mathlib.Algebra.MvPolynomial.Rename
public import Mathlib.RingTheory.Localization.Away.Basic
public import Mathlib.RingTheory.Localization.Ideal

/-!
# Localization after eliminating polynomial coordinates

Setting variables outside a subset to zero commutes with localization at any
polynomial, including polynomials whose image under elimination is zero. No
domain, nontriviality, or finiteness hypothesis is needed.
-/

@[expose] public section

set_option warningAsError true

noncomputable section

namespace MvPolynomial

universe u v

variable (K : Type u) [CommRing K] {σ : Type v} (S : Set σ)

/-- Evaluation at zero on the variables outside `S`, retaining the variables in `S`. -/
def eraseCoordinates : MvPolynomial σ K →ₐ[K] MvPolynomial S K :=
  killCompl (f := ((↑) : S → σ)) Subtype.val_injective

@[simp]
theorem eraseCoordinates_rename (p : MvPolynomial S K) :
    eraseCoordinates K S (rename ((↑) : S → σ) p) = p :=
  killCompl_rename_app Subtype.val_injective p

@[simp]
theorem eraseCoordinates_X_mem (i : σ) (hi : i ∈ S) :
    eraseCoordinates K S (X i) = X ⟨i, hi⟩ := by
  classical
  simp only [eraseCoordinates, killCompl, aeval_X]
  rw [dite_eq_left (show i ∈ Set.range ((↑) : S → σ) from ⟨⟨i, hi⟩, rfl⟩)]
  congr 1
  apply Subtype.ext
  exact Equiv.apply_ofInjective_symm Subtype.val_injective ⟨i, ⟨⟨i, hi⟩, rfl⟩⟩

@[simp]
theorem eraseCoordinates_X_not_mem (i : σ) (hi : i ∉ S) :
    eraseCoordinates K S (X i) = 0 := by
  classical
  simp only [eraseCoordinates, killCompl, aeval_X]
  rw [dite_eq_right (show i ∉ Set.range ((↑) : S → σ) from by
    rintro ⟨⟨_, hj⟩, rfl⟩
    exact hi hj)]

/-- The ideal of the localization generated by the coordinates outside `S`. -/
def localizedCoordinateIdeal (f : MvPolynomial σ K) : Ideal (Localization.Away f) :=
  Ideal.span (Set.range fun i : {i : σ // i ∉ S} =>
    algebraMap (MvPolynomial σ K) (Localization.Away f) (X i.1))

theorem quotient_killed (f : MvPolynomial σ K) (i : σ) (hi : i ∉ S) :
    (Ideal.Quotient.mkₐ K (localizedCoordinateIdeal K S f))
      (algebraMap (MvPolynomial σ K) (Localization.Away f) (X i)) = 0 := by
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  exact Ideal.subset_span ⟨⟨i, hi⟩, rfl⟩

def localizedCoordinateForwardBase (f : MvPolynomial σ K) :
    MvPolynomial σ K →ₐ[K] Localization.Away (eraseCoordinates K S f) :=
  (Algebra.algHom K (MvPolynomial S K) _).comp (eraseCoordinates K S)

theorem localizedCoordinateForwardBase_isUnit (f : MvPolynomial σ K) :
    IsUnit (localizedCoordinateForwardBase K S f f) := by
  exact IsLocalization.Away.algebraMap_isUnit (eraseCoordinates K S f)

def localizedCoordinateForwardAway (f : MvPolynomial σ K) :
    Localization.Away f →ₐ[K] Localization.Away (eraseCoordinates K S f) :=
  IsLocalization.Away.liftAlgHom f (localizedCoordinateForwardBase_isUnit K S f)

theorem localizedCoordinateForwardAway_base (f p : MvPolynomial σ K) :
    localizedCoordinateForwardAway K S f (algebraMap (MvPolynomial σ K) (Localization.Away f) p) =
      algebraMap (MvPolynomial S K) (Localization.Away (eraseCoordinates K S f))
        (eraseCoordinates K S p) := by
  exact IsLocalization.Away.lift_eq f (localizedCoordinateForwardBase_isUnit K S f) p

def localizedCoordinateForwardQuotient (f : MvPolynomial σ K) :
    (Localization.Away f ⧸ localizedCoordinateIdeal K S f) →ₐ[K]
      Localization.Away (eraseCoordinates K S f) :=
  Ideal.Quotient.liftₐ (localizedCoordinateIdeal K S f) (localizedCoordinateForwardAway K S f) (by
    intro x hx
    have h : localizedCoordinateIdeal K S f ≤
        RingHom.ker (localizedCoordinateForwardAway K S f).toRingHom :=
      Ideal.span_le.mpr (by
        rintro _ ⟨⟨i, hi⟩, rfl⟩
        change localizedCoordinateForwardAway K S f
            (algebraMap (MvPolynomial σ K) (Localization.Away f) (X i)) = 0
        rw [localizedCoordinateForwardAway_base, eraseCoordinates_X_not_mem K S i hi,
          map_zero])
    exact RingHom.mem_ker.mp (h hx))

theorem localizedCoordinateForwardQuotient_base (f p : MvPolynomial σ K) :
    localizedCoordinateForwardQuotient K S f ((Ideal.Quotient.mkₐ K (localizedCoordinateIdeal K S f))
      (algebraMap (MvPolynomial σ K) (Localization.Away f) p)) =
      algebraMap (MvPolynomial S K) (Localization.Away (eraseCoordinates K S f))
        (eraseCoordinates K S p) := by
  rw [localizedCoordinateForwardQuotient, Ideal.Quotient.liftₐ_apply]
  exact localizedCoordinateForwardAway_base K S f p

def localizedCoordinateInverseBase (f : MvPolynomial σ K) :
    MvPolynomial S K →ₐ[K] (Localization.Away f ⧸ localizedCoordinateIdeal K S f) :=
  aeval (fun i : S => (Ideal.Quotient.mkₐ K (localizedCoordinateIdeal K S f))
    (algebraMap (MvPolynomial σ K) (Localization.Away f) (X i.1)))

theorem localizedCoordinateInverseBase_erase (f : MvPolynomial σ K) :
    (localizedCoordinateInverseBase K S f).comp (eraseCoordinates K S) =
      (Ideal.Quotient.mkₐ K (localizedCoordinateIdeal K S f)).comp
        (Algebra.algHom K (MvPolynomial σ K) (Localization.Away f)) := by
  apply algHom_ext
  intro i
  by_cases hi : i ∈ S
  · simp only [AlgHom.comp_apply, eraseCoordinates_X_mem K S i hi,
      localizedCoordinateInverseBase, aeval_X]
    rfl
  · simp only [AlgHom.comp_apply, eraseCoordinates_X_not_mem K S i hi,
      map_zero]
    exact (quotient_killed K S f i hi).symm

theorem localizedCoordinateInverseBase_isUnit (f : MvPolynomial σ K) :
    IsUnit (localizedCoordinateInverseBase K S f (eraseCoordinates K S f)) := by
  have h := AlgHom.congr_fun (localizedCoordinateInverseBase_erase K S f) f
  simp only [AlgHom.comp_apply] at h
  rw [h]
  exact IsUnit.map (Ideal.Quotient.mkₐ K (localizedCoordinateIdeal K S f))
    (IsLocalization.Away.algebraMap_isUnit f)

def localizedCoordinateInverseAway (f : MvPolynomial σ K) :
    Localization.Away (eraseCoordinates K S f) →ₐ[K]
      (Localization.Away f ⧸ localizedCoordinateIdeal K S f) :=
  IsLocalization.Away.liftAlgHom (eraseCoordinates K S f)
    (localizedCoordinateInverseBase_isUnit K S f)

theorem localizedCoordinateInverseAway_base (f : MvPolynomial σ K) (p : MvPolynomial S K) :
    localizedCoordinateInverseAway K S f
      (algebraMap (MvPolynomial S K) (Localization.Away (eraseCoordinates K S f)) p) =
        localizedCoordinateInverseBase K S f p := by
  exact IsLocalization.Away.lift_eq (eraseCoordinates K S f)
    (localizedCoordinateInverseBase_isUnit K S f) p

/-- Eliminating a set of polynomial coordinates commutes with localization at `f`.
The result also applies if the erased polynomial is zero. -/
def localizedCoordinateQuotientEquiv (f : MvPolynomial σ K) :
    (Localization.Away f ⧸ localizedCoordinateIdeal K S f) ≃ₐ[K]
      Localization.Away (eraseCoordinates K S f) :=
  AlgEquiv.ofAlgHom (localizedCoordinateForwardQuotient K S f)
    (localizedCoordinateInverseAway K S f)
    (by
      apply Localization.algHom_ext
      apply algHom_ext
      intro i
      simp only [AlgHom.comp_apply, AlgHom.id_apply]
      change localizedCoordinateForwardQuotient K S f
        (localizedCoordinateInverseAway K S f
          (algebraMap (MvPolynomial S K) (Localization.Away (eraseCoordinates K S f)) (X i))) =
        algebraMap (MvPolynomial S K) (Localization.Away (eraseCoordinates K S f)) (X i)
      rw [localizedCoordinateInverseAway_base, localizedCoordinateInverseBase, aeval_X,
        localizedCoordinateForwardQuotient_base,
        eraseCoordinates_X_mem K S i.1 i.2])
    (by
      apply Ideal.Quotient.algHom_ext
      apply Localization.algHom_ext
      apply algHom_ext
      intro i
      simp only [AlgHom.comp_apply, AlgHom.id_apply]
      change localizedCoordinateInverseAway K S f
        (localizedCoordinateForwardQuotient K S f
          ((Ideal.Quotient.mkₐ K (localizedCoordinateIdeal K S f))
            (algebraMap (MvPolynomial σ K) (Localization.Away f) (X i)))) =
        (Ideal.Quotient.mkₐ K (localizedCoordinateIdeal K S f))
          (algebraMap (MvPolynomial σ K) (Localization.Away f) (X i))
      rw [localizedCoordinateForwardQuotient_base]
      by_cases hi : i ∈ S
      · rw [eraseCoordinates_X_mem K S i hi, localizedCoordinateInverseAway_base]
        simp [localizedCoordinateInverseBase]
      · rw [eraseCoordinates_X_not_mem K S i hi, map_zero, map_zero]
        exact (quotient_killed K S f i hi).symm)

@[simp]
theorem localizedCoordinateQuotientEquiv_algebraMap (f p : MvPolynomial σ K) :
    localizedCoordinateQuotientEquiv K S f
        ((Ideal.Quotient.mkₐ K (localizedCoordinateIdeal K S f))
          (algebraMap (MvPolynomial σ K) (Localization.Away f) p)) =
      algebraMap (MvPolynomial S K) (Localization.Away (eraseCoordinates K S f))
        (eraseCoordinates K S p) := by
  exact localizedCoordinateForwardQuotient_base K S f p

@[simp]
theorem localizedCoordinateQuotientEquiv_symm_algebraMap (f : MvPolynomial σ K)
    (p : MvPolynomial S K) :
    (localizedCoordinateQuotientEquiv K S f).symm
        (algebraMap (MvPolynomial S K) (Localization.Away (eraseCoordinates K S f)) p) =
      localizedCoordinateInverseBase K S f p := by
  exact localizedCoordinateInverseAway_base K S f p

@[simp]
theorem localizedCoordinateQuotientEquiv_coordinate (f : MvPolynomial σ K) (i : σ)
    (hi : i ∈ S) :
    localizedCoordinateQuotientEquiv K S f
        ((Ideal.Quotient.mkₐ K (localizedCoordinateIdeal K S f))
          (algebraMap (MvPolynomial σ K) (Localization.Away f) (X i))) =
      algebraMap (MvPolynomial S K) (Localization.Away (eraseCoordinates K S f))
        (X ⟨i, hi⟩) := by
  rw [localizedCoordinateQuotientEquiv_algebraMap, eraseCoordinates_X_mem K S i hi]

@[simp]
theorem localizedCoordinateQuotientEquiv_symm_coordinate (f : MvPolynomial σ K)
    (i : S) :
    (localizedCoordinateQuotientEquiv K S f).symm
      (algebraMap (MvPolynomial S K) (Localization.Away (eraseCoordinates K S f)) (X i)) =
      (Ideal.Quotient.mkₐ K (localizedCoordinateIdeal K S f))
        (algebraMap (MvPolynomial σ K) (Localization.Away f) (X i.1)) := by
  rw [localizedCoordinateQuotientEquiv_symm_algebraMap]
  simp [localizedCoordinateInverseBase]

end MvPolynomial
