/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import Mathlib.Algebra.CharP.Lemmas
public import Mathlib.RingTheory.HopfAlgebra.Primitive
public import Mathlib.RingTheory.HopfAlgebra.Quotient

/-!
# Principal Hopf ideals generated by powers of primitive elements

In characteristic `p`, the ideal generated by the `p ^ m`-th power of a primitive
element in a commutative Hopf algebra is stable under the counit, comultiplication,
and antipode. The statement includes `m = 0` and does not require a field base.

For the additive coordinate Hopf algebra, this specializes to the
characteristic-power quotient in Milne's *Algebraic Groups*, item 2.5. The
general primitive-element theorem and its proof use Mathlib's characteristic-power
binomial identity, primitive-element API and Hopf-ideal quotient conditions.

## References

- James S. Milne, *Algebraic Groups* (2017), item 2.5, p. 40 (the additive
  characteristic-power special case).
- Mathlib, `Mathlib.Algebra.CharP.Lemmas`,
  `Mathlib.RingTheory.Bialgebra.Primitive`,
  `Mathlib.RingTheory.HopfAlgebra.Primitive`, and
  `Mathlib.RingTheory.HopfAlgebra.Quotient` (the characteristic-power identity,
  primitive counit/comultiplication/antipode laws and quotient conditions).
-/

public section

open scoped TensorProduct

namespace Bialgebra.IsPrimitiveElem

variable {K A : Type*} [CommRing K] [CommRing A] [HopfAlgebra K A]
  {p : ℕ} [Fact p.Prime] [CharP K p] {a : A}

/-- The principal ideal generated by a characteristic-power of a primitive element is a
Hopf ideal, including the first power at `m = 0`. This applies in particular to
the additive-coordinate example of Milne's *Algebraic Groups*, item 2.5;
the argument here applies to any commutative Hopf algebra over a commutative base. -/
theorem isHopfIdeal_span_pow_char_pow (ha : Bialgebra.IsPrimitiveElem K a) (m : ℕ) :
    Ideal.IsHopfIdeal K (Ideal.span {a ^ (p ^ m)}) := by
  let I : Ideal A := Ideal.span {a ^ (p ^ m)}
  let quotient : A →ₐ[K] A ⧸ I := Ideal.Quotient.mkₐ K I
  let comulQuotient : A →ₐ[K] (A ⧸ I) ⊗[K] (A ⧸ I) :=
    (Algebra.TensorProduct.map quotient quotient).comp (Bialgebra.comulAlgHom K A)
  have hCounit : (Bialgebra.counitAlgHom K A) (a ^ (p ^ m)) = 0 := by
    rw [map_pow, show (Bialgebra.counitAlgHom K A) a = (0 : K) from ha.counit_eq_zero,
      zero_pow (ne_of_gt (pow_pos (Fact.out : p.Prime).pos m))]
  have hComul : comulQuotient (a ^ (p ^ m)) = 0 := by
    have hpK : (p : K) = 0 := CharP.cast_eq_zero K p
    have hpTensor : (p : (A ⧸ I) ⊗[K] (A ⧸ I)) = 0 := by
      calc
        (p : (A ⧸ I) ⊗[K] (A ⧸ I)) =
            algebraMap K ((A ⧸ I) ⊗[K] (A ⧸ I)) (p : K) :=
              (map_natCast (algebraMap K _) p).symm
        _ = 0 := by rw [hpK]; simp
    rw [map_pow]
    change ((Algebra.TensorProduct.map quotient quotient)
      (Coalgebra.comul (R := K) a)) ^ (p ^ m) = 0
    rw [ha.comul_eq_tmul_add_tmul]
    simp only [map_add, Algebra.TensorProduct.map_tmul]
    rw [(Commute.all _ _).add_pow_prime_pow_eq' (Fact.out : p.Prime) m, hpTensor]
    have hq : (quotient a) ^ (p ^ m) = 0 := by
      rw [← map_pow]
      exact Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.mem_span_singleton_self _)
    simp [hq]
  have hCounitIdeal : ∀ ⦃x : A⦄, x ∈ I → Coalgebra.counit (R := K) x = 0 := by
    intro x hx
    obtain ⟨b, hb⟩ := Ideal.mem_span_singleton'.mp hx
    rw [← hb]
    change (Bialgebra.counitAlgHom K A) (b * a ^ (p ^ m)) = 0
    rw [map_mul, hCounit, mul_zero]
  have hComulIdeal : ∀ ⦃x : A⦄, x ∈ I →
      _root_.TensorProduct.map (I.restrictScalars K).mkQ (I.restrictScalars K).mkQ
        (Coalgebra.comul (R := K) x) = 0 := by
    intro x hx
    obtain ⟨b, hb⟩ := Ideal.mem_span_singleton'.mp hx
    rw [← hb]
    change comulQuotient (b * a ^ (p ^ m)) = 0
    rw [map_mul, hComul, mul_zero]
  have hAntipode : ∀ ⦃x : A⦄, x ∈ I → HopfAlgebra.antipode K x ∈ I := by
    intro x hx
    obtain ⟨b, hb⟩ := Ideal.mem_span_singleton'.mp hx
    rw [← hb]
    change (HopfAlgebra.antipodeAlgHom K A) (b * a ^ (p ^ m)) ∈ I
    rw [map_mul, map_pow]
    change (HopfAlgebra.antipodeAlgHom K A) b *
      (HopfAlgebra.antipode K a) ^ (p ^ m) ∈ I
    rw [ha.antipode_eq_neg]
    exact I.mul_mem_left _ (Ideal.mem_span_singleton.mpr
      (pow_dvd_pow_of_dvd (dvd_neg.mpr dvd_rfl) (p ^ m)))
  exact { counit_eq_zero := hCounitIdeal
          map_mkQ_comul_eq_zero := hComulIdeal
          antipode_mem := hAntipode }

end Bialgebra.IsPrimitiveElem
