/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import AlgebraicGroups.GroupScheme.GeneralLinearDeterminant
public import Mathlib.RingTheory.HopfAlgebra.Quotient

/-!
# The determinant-one quotient of the finite general linear coordinate ring

The ideal generated by the determinant of the universal invertible matrix minus one
is a Hopf ideal over every commutative base ring, including the zero ring.
-/

@[expose] public section

noncomputable section

open GeneralLinearCoordinateRing
open scoped TensorProduct

universe u

namespace SpecialLinearCoordinateRing

variable (K : Type u) [CommRing K] (n : Type u) [Fintype n] [DecidableEq n]

/-- The determinant-one ideal inside the *localized* general linear coordinate algebra. -/
def determinantOneIdeal : Ideal (CoordinateRing K n) :=
  Ideal.span { (matrix K n).det - 1 }

/-- The coordinate algebra representing determinant-one invertible matrices. -/
abbrev CoordinateRing := GeneralLinearCoordinateRing.CoordinateRing K n ⧸ determinantOneIdeal K n

/-- The canonical surjective quotient of the actual general linear coordinate algebra. -/
def quotient : GeneralLinearCoordinateRing.CoordinateRing K n →ₐ[K] CoordinateRing K n :=
  Ideal.Quotient.mkₐ K (determinantOneIdeal K n)

theorem quotient_det :
    quotient K n (matrix K n).det = 1 := by
  have hz : quotient K n ((matrix K n).det - 1) = 0 :=
    Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.mem_span_singleton_self _)
  simpa only [map_sub, map_one, sub_eq_zero] using hz

@[simp] theorem quotient_detInverse :
    quotient K n (detInverse K n) = 1 := by
  have h := congrArg (quotient K n) (det_mul_detInverse K n)
  rw [map_mul, map_one, quotient_det, one_mul] at h
  exact h

set_option linter.style.haveILetI false in
/-- The actual determinant-one ideal satisfies counit, quotient-comultiplication,
and antipode stability, without flatness or nontriviality assumptions. -/
theorem determinantOneIdeal_isHopfIdeal_proof : (determinantOneIdeal K n).IsHopfIdeal K := by
  let ideal := determinantOneIdeal K n
  let quotientMap : GeneralLinearCoordinateRing.CoordinateRing K n →ₐ[K]
      (GeneralLinearCoordinateRing.CoordinateRing K n ⧸ ideal) := Ideal.Quotient.mkₐ K ideal
  let comulQuotient : GeneralLinearCoordinateRing.CoordinateRing K n →ₐ[K]
      (GeneralLinearCoordinateRing.CoordinateRing K n ⧸ ideal) ⊗[K]
        (GeneralLinearCoordinateRing.CoordinateRing K n ⧸ ideal) :=
    (Algebra.TensorProduct.map quotientMap quotientMap).comp
      (Bialgebra.comulAlgHom K (GeneralLinearCoordinateRing.CoordinateRing K n))
  letI : CommRing
      ((GeneralLinearCoordinateRing.CoordinateRing K n ⧸ ideal) ⊗[K]
        (GeneralLinearCoordinateRing.CoordinateRing K n ⧸ ideal)) := inferInstance
  have hq : quotientMap (matrix K n).det = 1 := quotient_det K n
  have hcounit : (Bialgebra.counitAlgHom K
      (GeneralLinearCoordinateRing.CoordinateRing K n)) ((matrix K n).det - 1) = 0 := by
    rw [map_sub, map_one]
    change Coalgebra.counit (R := K) (matrix K n).det - 1 = 0
    rw [AlgebraicGeometry.generalLinearDeterminant_counit, sub_self]
  have hcomul : comulQuotient ((matrix K n).det - 1) = 0 := by
    rw [map_sub, map_one, sub_eq_zero]
    change (Algebra.TensorProduct.map quotientMap quotientMap)
      (Coalgebra.comul (R := K) (matrix K n).det) = 1
    rw [AlgebraicGeometry.generalLinearDeterminant_comul,
      Algebra.TensorProduct.map_tmul, hq]
    exact Algebra.TensorProduct.one_def.symm
  have hantipode : HopfAlgebra.antipode K ((matrix K n).det - 1) ∈ ideal := by
    change (HopfAlgebra.antipodeAlgHom K
      (GeneralLinearCoordinateRing.CoordinateRing K n)) ((matrix K n).det - 1) ∈ ideal
    rw [map_sub, map_one]
    change HopfAlgebra.antipode K (matrix K n).det - 1 ∈ ideal
    rw [AlgebraicGeometry.generalLinearDeterminant_antipode]
    change detInverse K n - 1 ∈ determinantOneIdeal K n
    apply Ideal.mem_span_singleton.mpr
    refine ⟨-detInverse K n, ?_⟩
    calc
      detInverse K n - 1 = -((matrix K n).det * detInverse K n) + detInverse K n := by
        rw [det_mul_detInverse]; ring
      _ = ((matrix K n).det - 1) * -detInverse K n := by ring
  refine { counit_eq_zero := ?_, map_mkQ_comul_eq_zero := ?_, antipode_mem := ?_ }
  · intro x hx
    obtain ⟨a, ha⟩ := Ideal.mem_span_singleton'.mp hx
    rw [← ha]
    change (Bialgebra.counitAlgHom K _) (a * ((matrix K n).det - 1)) = 0
    rw [map_mul, hcounit, mul_zero]
  · intro x hx
    obtain ⟨a, ha⟩ := Ideal.mem_span_singleton'.mp hx
    rw [← ha]
    change comulQuotient (a * ((matrix K n).det - 1)) = 0
    rw [map_mul, hcomul]
    exact mul_zero _
  · intro x hx
    obtain ⟨a, ha⟩ := Ideal.mem_span_singleton'.mp hx
    rw [← ha]
    change (HopfAlgebra.antipodeAlgHom K _) (a * ((matrix K n).det - 1)) ∈ ideal
    rw [map_mul]
    exact ideal.mul_mem_left _ hantipode

instance determinantOneIdeal_isHopfIdeal : (determinantOneIdeal K n).IsHopfIdeal K :=
  determinantOneIdeal_isHopfIdeal_proof K n

/-- The determinant-one ideal in the polynomial matrix coordinate ring. -/
def polynomialIdeal : Ideal (PolynomialRing K n) :=
  Ideal.span {determinant K n - 1}

/-- The polynomial presentation of the determinant-one coordinate ring. -/
abbrev PolynomialCoordinateRing := PolynomialRing K n ⧸ polynomialIdeal K n

/-- The polynomial determinant becomes one after imposing the determinant-one relation. -/
theorem polynomialQuotient_det :
    (Ideal.Quotient.mkₐ K (polynomialIdeal K n)) (determinant K n) = 1 := by
  have hz : (Ideal.Quotient.mkₐ K (polynomialIdeal K n)) (determinant K n - 1) = 0 :=
    Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.mem_span_singleton_self _)
  simpa only [map_sub, map_one, sub_eq_zero] using hz

/-- Extending determinant-one polynomial evaluation across the determinant localization. -/
def localizationToPolynomialQuotient :
    GeneralLinearCoordinateRing.CoordinateRing K n →ₐ[K] PolynomialCoordinateRing K n :=
  IsLocalization.Away.liftAlgHom (determinant K n)
    (f := Ideal.Quotient.mkₐ K (polynomialIdeal K n)) (by
      rw [polynomialQuotient_det]
      exact isUnit_one)

/-- Evaluate the universal polynomial variables in the localized determinant-one ring. -/
def polynomialToCoordinateRing : PolynomialRing K n →ₐ[K] CoordinateRing K n :=
  (quotient K n).comp
    (IsScalarTower.toAlgHom K (PolynomialRing K n)
      (GeneralLinearCoordinateRing.CoordinateRing K n))

@[simp] theorem polynomialToCoordinateRing_det :
    polynomialToCoordinateRing K n (determinant K n) = 1 := by
  change quotient K n (algebraMap (PolynomialRing K n)
    (GeneralLinearCoordinateRing.CoordinateRing K n) (determinant K n)) = 1
  rw [← matrix_det, quotient_det]

/-- The canonical map from the polynomial presentation to the Hopf quotient. -/
def polynomialQuotientToCoordinateRing :
    PolynomialCoordinateRing K n →ₐ[K] CoordinateRing K n :=
  Ideal.Quotient.liftₐ (polynomialIdeal K n) (polynomialToCoordinateRing K n) (by
    intro polynomial membership
    obtain ⟨multiplier, hmultiplier⟩ := Ideal.mem_span_singleton'.mp membership
    rw [← hmultiplier, map_mul, map_sub, map_one,
      polynomialToCoordinateRing_det, sub_self, mul_zero])

/-- The canonical map from the Hopf quotient to the polynomial presentation. -/
def coordinateRingToPolynomialQuotient :
    CoordinateRing K n →ₐ[K] PolynomialCoordinateRing K n :=
  Ideal.Quotient.liftₐ (determinantOneIdeal K n)
    (localizationToPolynomialQuotient K n) (by
      intro element membership
      obtain ⟨multiplier, hmultiplier⟩ := Ideal.mem_span_singleton'.mp membership
      rw [← hmultiplier, map_mul, map_sub, map_one]
      have hdet : localizationToPolynomialQuotient K n (matrix K n).det = 1 := by
        rw [matrix_det]
        simp only [localizationToPolynomialQuotient,
          IsLocalization.Away.liftAlgHom_apply, IsLocalization.Away.lift_eq]
        exact polynomialQuotient_det K n
      rw [hdet, sub_self, mul_zero])

theorem coordinateRingToPolynomialQuotient_comp_quotient :
    (coordinateRingToPolynomialQuotient K n).comp (quotient K n) =
      localizationToPolynomialQuotient K n := by
  exact Ideal.Quotient.liftₐ_comp _ _ _

theorem polynomialQuotientToCoordinateRing_comp_quotient :
    (polynomialQuotientToCoordinateRing K n).comp
        (Ideal.Quotient.mkₐ K (polynomialIdeal K n)) =
      polynomialToCoordinateRing K n := by
  exact Ideal.Quotient.liftₐ_comp _ _ _

theorem coordinateRingToPolynomialQuotient_comp_polynomialQuotientTo :
    (coordinateRingToPolynomialQuotient K n).comp
        (polynomialQuotientToCoordinateRing K n) =
      AlgHom.id K (PolynomialCoordinateRing K n) := by
  apply Ideal.Quotient.algHom_ext K
  rw [AlgHom.comp_assoc, polynomialQuotientToCoordinateRing_comp_quotient]
  apply MvPolynomial.algHom_ext
  intro ⟨i, j⟩
  change (coordinateRingToPolynomialQuotient K n)
    (quotient K n (algebraMap (PolynomialRing K n)
      (GeneralLinearCoordinateRing.CoordinateRing K n) (MvPolynomial.X (i, j)))) =
      (Ideal.Quotient.mkₐ K (polynomialIdeal K n)) (MvPolynomial.X (i, j))
  rw [← AlgHom.comp_apply, coordinateRingToPolynomialQuotient_comp_quotient]
  simp only [localizationToPolynomialQuotient, IsLocalization.Away.liftAlgHom_apply,
    IsLocalization.Away.lift_eq, AlgHom.toRingHom_eq_coe]
  rfl

theorem polynomialQuotientToCoordinateRing_comp_coordinateRingTo :
    (polynomialQuotientToCoordinateRing K n).comp
        (coordinateRingToPolynomialQuotient K n) =
      AlgHom.id K (CoordinateRing K n) := by
  apply Ideal.Quotient.algHom_ext K
  rw [AlgHom.comp_assoc]
  change (polynomialQuotientToCoordinateRing K n).comp
    ((coordinateRingToPolynomialQuotient K n).comp (quotient K n)) =
      (AlgHom.id K (CoordinateRing K n)).comp (quotient K n)
  rw [coordinateRingToPolynomialQuotient_comp_quotient]
  apply IsLocalization.algHom_ext (Submonoid.powers (determinant K n))
  apply MvPolynomial.algHom_ext
  intro ⟨i, j⟩
  change (polynomialQuotientToCoordinateRing K n)
    ((localizationToPolynomialQuotient K n)
      (algebraMap (PolynomialRing K n)
        (GeneralLinearCoordinateRing.CoordinateRing K n) (MvPolynomial.X (i, j)))) =
      (quotient K n) (algebraMap (PolynomialRing K n)
        (GeneralLinearCoordinateRing.CoordinateRing K n) (MvPolynomial.X (i, j)))
  simp only [localizationToPolynomialQuotient, IsLocalization.Away.liftAlgHom_apply,
    IsLocalization.Away.lift_eq, AlgHom.toRingHom_eq_coe]
  change (polynomialQuotientToCoordinateRing K n)
    ((Ideal.Quotient.mkₐ K (polynomialIdeal K n)) (MvPolynomial.X (i, j))) = _
  rw [← AlgHom.comp_apply, polynomialQuotientToCoordinateRing_comp_quotient]
  rfl

/-- Explicitly identify the polynomial determinant-one presentation with the
determinant-one Hopf quotient of the localized GL coordinate algebra. -/
def polynomialEquiv : PolynomialCoordinateRing K n ≃ₐ[K] CoordinateRing K n :=
  AlgEquiv.ofAlgHom (polynomialQuotientToCoordinateRing K n)
    (coordinateRingToPolynomialQuotient K n)
    (polynomialQuotientToCoordinateRing_comp_coordinateRingTo K n)
    (coordinateRingToPolynomialQuotient_comp_polynomialQuotientTo K n)

/-- An entry of the determinant-one universal matrix. -/
def entry (i j : n) : CoordinateRing K n := quotient K n (matrix K n i j)

theorem polynomialEquiv_variable (i j : n) :
    polynomialEquiv K n
      ((Ideal.Quotient.mkₐ K (polynomialIdeal K n)) (MvPolynomial.X (i, j))) =
        entry K n i j := by
  change (polynomialQuotientToCoordinateRing K n)
    ((Ideal.Quotient.mkₐ K (polynomialIdeal K n)) (MvPolynomial.X (i, j))) =
      polynomialToCoordinateRing K n (MvPolynomial.X (i, j))
  rw [← AlgHom.comp_apply, polynomialQuotientToCoordinateRing_comp_quotient]

theorem determinant_entry :
    Matrix.det (fun i j ↦ entry K n i j : Matrix n n (CoordinateRing K n)) = 1 := by
  change ((quotient K n).toRingHom.mapMatrix (matrix K n)).det = 1
  rw [← RingHom.map_det]
  exact quotient_det K n

theorem polynomialEquiv_symm_detInverse :
    (polynomialEquiv K n).symm (quotient K n (detInverse K n)) = 1 := by
  rw [quotient_detInverse]
  exact map_one _

end SpecialLinearCoordinateRing

#lint
