/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import AlgebraicGroups.Algebra.UnitriangularStageCoordinates

/-!
# The algebraic zero fiber of a positive unitriangular stage

At any positive superdiagonal stage, the successor quotient is universal
among algebra maps that annihilate every coordinate on that superdiagonal.
This statement holds over arbitrary commutative coefficient algebras.

The algebra-map factorization here is distinct from the scheme-theoretic
kernel square, which is proved directly using quotient-spectrum lifting.

## References

* J. S. Milne, *Algebraic Groups* (2017), §6.49 (one-entry additive
  quotients in the finer field-case filtration).
* Mathlib contributors, the ideal-span and `Ideal.Quotient.liftₐ`
  universal properties used for successor factorization.
* The existing `UnitriangularStageCoordinateRing` gives the quotient and coordinates.
-/

@[expose] public section

noncomputable section

namespace UnitriangularStageCoordinateRing

variable (K : Type) [CommRing K] (n r : ℕ)

set_option maxHeartbeats 1500000

/-- The underlying algebra map of a primitive coordinate is its symmetric-algebra lift. -/
@[simp] theorem coordinateBialgHom_toAlgHom (hr : 1 ≤ r)
    (ij : Matrix.UnitriangularGroup.superdiagonalIndex n r) :
    (coordinateBialgHom K n r hr ij :
      AlgebraicGeometry.additiveGroupCoordinateRing K →ₐ[K] CoordinateRing K n r) =
        coordinateAlgHom K n r ij := rfl

/-- The next ideal is generated by the old forbidden entries and exactly the
entries on the current superdiagonal. Milne, *Algebraic Groups* (2017), §6.49
removes individual entries over a field; this identity treats a whole stage. -/
theorem ideal_succ_eq_sup (hr : 1 ≤ r) :
    ideal K n (r + 1) = ideal K n r ⊔
      Ideal.span (Set.range (fun ij : Matrix.UnitriangularGroup.superdiagonalIndex n r =>
        entry K n ij.1.1 ij.1.2)) := by
  apply le_antisymm
  · apply Ideal.span_le.mpr
    rintro _ ⟨i, j, hij, hgap, rfl⟩
    by_cases hsmall : j.val < i.val + r
    · exact Ideal.mem_sup_left (entry_mem K n r i j hij hsmall)
    · have heq : j.val = i.val + r := by omega
      have hspan : entry K n i j ∈
          Ideal.span (Set.range (fun ij : Matrix.UnitriangularGroup.superdiagonalIndex n r =>
            entry K n ij.1.1 ij.1.2)) :=
        Ideal.subset_span ⟨⟨(i, j), heq⟩, rfl⟩
      exact Ideal.mem_sup_right hspan
  · apply sup_le
    · exact ideal_le_succ K n r
    · apply Ideal.span_le.mpr
      rintro _ ⟨ij, rfl⟩
      have hij : ij.1.1 < ij.1.2 := by have := ij.2; omega
      exact entry_mem K n (r + 1) _ _ hij (by omega)

/-- A stage evaluation extends uniquely across the closed successor precisely
when its current superdiagonal coordinates vanish. Milne, *Algebraic Groups*
(2017), §6.49 gives one-entry field-case additive quotients; this algebra-map
universal property is over arbitrary commutative coefficient algebras. -/
theorem existsUnique_comp_successor {R : Type} [CommRing R] [Algebra K R]
    (hr : 1 ≤ r)
    (f : CoordinateRing K n r →ₐ[K] R)
    (hcoord : ∀ ij : Matrix.UnitriangularGroup.superdiagonalIndex n r,
      f (coordinate K n r ij) = 0) :
    ∃! g : CoordinateRing K n (r + 1) →ₐ[K] R,
      g.comp (successor K n r) = f := by
  let ambientMap := f.comp (quotient K n r)
  have hI : ∀ x : Ambient K n, x ∈ ideal K n (r + 1) → ambientMap x = 0 := by
    intro x hx
    have hker : ideal K n (r + 1) ≤ RingHom.ker ambientMap.toRingHom := by
      rw [ideal_succ_eq_sup K n r hr]
      apply sup_le
      · intro y hy
        apply RingHom.mem_ker.mpr
        change f (quotient K n r y) = 0
        change f (Ideal.Quotient.mk (ideal K n r) y) = 0
        rw [Ideal.Quotient.eq_zero_iff_mem.mpr hy, map_zero]
      · apply Ideal.span_le.mpr
        rintro _ ⟨ij, rfl⟩
        apply RingHom.mem_ker.mpr
        exact hcoord ij
    exact RingHom.mem_ker.mp (hker hx)
  let lift : CoordinateRing K n (r + 1) →ₐ[K] R :=
    Ideal.Quotient.liftₐ (ideal K n (r + 1)) ambientMap hI
  refine ⟨lift, ?_, ?_⟩
  · apply Ideal.Quotient.algHom_ext K
    change (lift.comp (successor K n r)).comp (quotient K n r) =
      f.comp (quotient K n r)
    rw [AlgHom.comp_assoc]
    exact Ideal.Quotient.liftₐ_comp (ideal K n (r + 1)) ambientMap hI
  · intro g hg
    apply Ideal.Quotient.algHom_ext K
    have hcomp := congrArg (fun a : CoordinateRing K n r →ₐ[K] R =>
      a.comp (quotient K n r)) hg
    change g.comp (quotient K n (r + 1)) = ambientMap at hcomp
    exact hcomp.trans
      (Ideal.Quotient.liftₐ_comp (ideal K n (r + 1)) ambientMap hI).symm

end UnitriangularStageCoordinateRing
