/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import AlgebraicGroups.GroupTheory.UnitriangularCentralFiltration

/-!
# Closed superdiagonal unitriangular Hopf quotients

The stage ideal is generated by the forbidden strict upper entries of the
unitriangular coordinate Hopf algebra. Its Hopf structure holds over every
commutative base ring, without any reducedness or flatness assumptions.

Milne's field-case filtration removes individual upper entries; its
superdiagonal block endpoints give the field-case stages here. The Hopf
quotients extend these entire-superdiagonal stages to arbitrary bases.

## References

* J. S. Milne, *Algebraic Groups* (2017), item 2.9 (the unitriangular
  algebraic group and its polynomial presentation) and §6.49 (the finer
  filtration by individual entries).
* Mathlib contributors, `Mathlib.RingTheory.HopfAlgebra.Quotient`
  (Hopf ideals and quotient structure).
* The existing `UnitriangularCoordinateRing` and `Matrix.UnitriangularGroup`
  supply the full-group coordinates and point-group filtration.
-/

@[expose] public section

noncomputable section

open GeneralLinearCoordinateRing UnitriangularCoordinateRing
open scoped TensorProduct

namespace UnitriangularStageCoordinateRing

variable (K : Type) [CommRing K] (n r : ℕ)

abbrev Ambient := UnitriangularCoordinateRing.CoordinateRing K (Fin n)

/-- Universal strict upper entry in the ambient Hopf algebra. -/
def entry (i j : Fin n) : Ambient K n :=
  UnitriangularCoordinateRing.quotient K (Fin n)
    (GeneralLinearCoordinateRing.matrix K (Fin n) i j)

/-- The ideal generated by upper entries below the `r`-th superdiagonal.
Milne, *Algebraic Groups* (2017), §6.49 gives finer field-case subgroups
defined by vanishing individual entries. -/
def ideal : Ideal (Ambient K n) :=
  Ideal.span {x | ∃ i j : Fin n, i < j ∧ j.val < i.val + r ∧ x = entry K n i j}

abbrev CoordinateRing := Ambient K n ⧸ ideal K n r

/-- The canonical map from the full unitriangular coordinate Hopf algebra. -/
def quotient : Ambient K n →ₐ[K] CoordinateRing K n r :=
  Ideal.Quotient.mkₐ K (ideal K n r)

theorem entry_mem (i j : Fin n) (hij : i < j) (hgap : j.val < i.val + r) :
    entry K n i j ∈ ideal K n r :=
  Ideal.subset_span ⟨i, j, hij, hgap, rfl⟩

@[simp] theorem quotient_entry (i j : Fin n) (hij : i < j)
    (hgap : j.val < i.val + r) : quotient K n r (entry K n i j) = 0 :=
  Ideal.Quotient.eq_zero_iff_mem.mpr (entry_mem K n r i j hij hgap)

/-- An evaluation factors through the stage precisely when its matrix lies in
the existing superdiagonal subgroup. Milne, *Algebraic Groups* (2017),
§6.49 describes the finer individual-entry field-case filtration whose
superdiagonal block endpoints give these stages. -/
theorem mem_stage_iff {R : Type} [CommRing R] [Algebra K R]
    (f : Ambient K n →ₐ[K] R) :
    ideal K n r ≤ RingHom.ker f.toRingHom ↔
      AlgebraicGeometry.unitriangularToGL K (Fin n) R f ∈
        Matrix.UnitriangularGroup.superdiagonalSubgroup n R r := by
  constructor
  · intro hf
    apply (Matrix.UnitriangularGroup.mem_superdiagonalSubgroup _ _ _).mpr
    intro i j hgap
    by_cases hij : i < j
    · have hz : f (entry K n i j) = 0 :=
        RingHom.mem_ker.mp (hf (entry_mem K n r i j hij hgap))
      change f (entry K n i j) - (if i = j then 1 else 0) = 0
      simp [hz, ne_of_lt hij]
    · by_cases heq : i = j
      · subst j
        have hd := (AlgebraicGeometry.unitriangularToGL K (Fin n) R f).2.2 i
        change f (entry K n i i) = 1 at hd
        change f (entry K n i i) - (if i = i then 1 else 0) = 0
        simp [hd]
      · have hji : j < i := lt_of_le_of_ne (le_of_not_gt hij) (Ne.symm heq)
        have hz := (AlgebraicGeometry.unitriangularToGL K (Fin n) R f).2.1 hji
        change f (entry K n i j) = 0 at hz
        change f (entry K n i j) - (if i = j then 1 else 0) = 0
        simp [hz, heq]
  · intro hg
    apply Ideal.span_le.mpr
    rintro _ ⟨i, j, hij, hgap, rfl⟩
    apply RingHom.mem_ker.mpr
    have hz := (Matrix.UnitriangularGroup.mem_superdiagonalSubgroup _ _ _).mp
      hg i j hgap
    change f (entry K n i j) = 0
    change f (entry K n i j) - (if i = j then 1 else 0) = 0 at hz
    simpa [ne_of_lt hij] using hz

theorem counit_zero {x : Ambient K n} (hx : x ∈ ideal K n r) :
    Coalgebra.counit (R := K) x = 0 := by
  have h : ideal K n r ≤
      RingHom.ker (Bialgebra.counitAlgHom K (Ambient K n)).toRingHom := by
    apply Ideal.span_le.mpr
    rintro _ ⟨i, j, hij, hgap, rfl⟩
    apply RingHom.mem_ker.mpr
    change Coalgebra.counit (R := K)
      (Ideal.Quotient.mk (UnitriangularCoordinateRing.ideal K (Fin n))
        (GeneralLinearCoordinateRing.matrix K (Fin n) i j)) = 0
    rw [Bialgebra.Quotient.counit_mk, GeneralLinearCoordinateRing.native_counit_matrix]
    simp [ne_of_lt hij]
  change (Bialgebra.counitAlgHom K (Ambient K n)) x = 0
  exact RingHom.mem_ker.mp (h hx)

/-- Antipode evaluation is inversion for every coefficient algebra. -/
theorem toGL_antipode {R : Type} [CommRing R] [Algebra K R]
    (f : Ambient K n →ₐ[K] R) :
    AlgebraicGeometry.unitriangularToGL K (Fin n) R
      (f.comp (HopfAlgebra.antipodeAlgHom K (Ambient K n))) =
      (AlgebraicGeometry.unitriangularToGL K (Fin n) R f)⁻¹ := by
  apply Subtype.ext
  apply Matrix.GeneralLinearGroup.ext
  intro i j
  change f (HopfAlgebra.antipode K
    (Ideal.Quotient.mk (UnitriangularCoordinateRing.ideal K (Fin n))
      (GeneralLinearCoordinateRing.matrix K (Fin n) i j))) =
    ((GeneralLinearCoordinateRing.toGL
      (f.comp (UnitriangularCoordinateRing.quotient K (Fin n))))⁻¹) i j
  rw [HopfAlgebra.Quotient.antipode_mk, GeneralLinearCoordinateRing.native_antipode_matrix]
  exact (congrArg (fun g : Matrix.GeneralLinearGroup (Fin n) R => g i j)
    ((Matrix.GeneralLinearGroup.map
      (f.comp (UnitriangularCoordinateRing.quotient K (Fin n))).toRingHom).map_inv
        (GeneralLinearCoordinateRing.universal K (Fin n)))).symm

theorem antipode_mem {x : Ambient K n} (hx : x ∈ ideal K n r) :
    HopfAlgebra.antipode K x ∈ ideal K n r := by
  let q : @AlgHom K (Ambient K n) (CoordinateRing K n r)
      CommRing.toCommSemiring
      (Ideal.Quotient.semiring (UnitriangularCoordinateRing.ideal K (Fin n)))
      CommRing.toCommSemiring.toSemiring
      (Ideal.instAlgebraQuotient K (UnitriangularCoordinateRing.ideal K (Fin n)))
      (Ideal.instAlgebraQuotient K (ideal K n r)) := {
    toFun := fun x => Ideal.Quotient.mk (ideal K n r) x
    map_zero' := rfl
    map_one' := rfl
    map_add' := fun _ _ => rfl
    map_mul' := fun _ _ => rfl
    commutes' := fun _ => rfl
  }
  have hpoint : AlgebraicGeometry.unitriangularToGL K (Fin n) (CoordinateRing K n r) q ∈
      Matrix.UnitriangularGroup.superdiagonalSubgroup n (CoordinateRing K n r) r := by
    apply (Matrix.UnitriangularGroup.mem_superdiagonalSubgroup _ _ _).mpr
    intro i j hgap
    by_cases hij : i < j
    · change q (entry K n i j) - (if i = j then 1 else 0) = 0
      have hz : q (entry K n i j) = 0 :=
        Ideal.Quotient.eq_zero_iff_mem.mpr (entry_mem K n r i j hij hgap)
      simpa [ne_of_lt hij] using hz
    · by_cases heq : i = j
      · subst j
        have hd := (AlgebraicGeometry.unitriangularToGL K (Fin n)
          (CoordinateRing K n r) q).2.2 i
        change q (entry K n i i) = 1 at hd
        change q (entry K n i i) - (if i = i then 1 else 0) = 0
        simp [hd]
      · have hji : j < i := lt_of_le_of_ne (le_of_not_gt hij) (Ne.symm heq)
        have hz := (AlgebraicGeometry.unitriangularToGL K (Fin n)
          (CoordinateRing K n r) q).2.1 hji
        change q (entry K n i j) = 0 at hz
        change q (entry K n i j) - (if i = j then 1 else 0) = 0
        simp [hz, heq]
  have hantiPoint : AlgebraicGeometry.unitriangularToGL K (Fin n)
      (CoordinateRing K n r) (q.comp (HopfAlgebra.antipodeAlgHom K (Ambient K n))) ∈
      Matrix.UnitriangularGroup.superdiagonalSubgroup n (CoordinateRing K n r) r := by
    have hinv : AlgebraicGeometry.unitriangularToGL K (Fin n) (CoordinateRing K n r)
        (q.comp (HopfAlgebra.antipodeAlgHom K (Ambient K n))) =
        (AlgebraicGeometry.unitriangularToGL K (Fin n) (CoordinateRing K n r) q)⁻¹ := by
      with_reducible_and_instances
        exact toGL_antipode K n (R := CoordinateRing K n r) q
    exact hinv.symm ▸
      (Matrix.UnitriangularGroup.superdiagonalSubgroup n (CoordinateRing K n r) r).inv_mem
        hpoint
  have hantiKer : ideal K n r ≤
      RingHom.ker (q.comp (HopfAlgebra.antipodeAlgHom K (Ambient K n))).toRingHom :=
    (mem_stage_iff K n r _).mpr hantiPoint
  exact Ideal.Quotient.eq_zero_iff_mem.mp (RingHom.mem_ker.mp (hantiKer hx))

set_option maxHeartbeats 500000
set_option linter.style.haveILetI false

theorem comul_entry (i j : Fin n) :
    Coalgebra.comul (R := K) (entry K n i j) =
      ∑ k : Fin n, entry K n i k ⊗ₜ[K] entry K n k j := by
  change Coalgebra.comul (R := K)
    (Ideal.Quotient.mk (UnitriangularCoordinateRing.ideal K (Fin n))
      (GeneralLinearCoordinateRing.matrix K (Fin n) i j)) = _
  rw [Bialgebra.Quotient.comul_mk, GeneralLinearCoordinateRing.native_comul_matrix]
  simp only [map_sum, TensorProduct.map_tmul]
  rfl

theorem comul_zero {x : Ambient K n} (hx : x ∈ ideal K n r) :
    (Algebra.TensorProduct.map (quotient K n r) (quotient K n r))
      (Coalgebra.comul (R := K) x) = 0 := by
  letI : AddCommMonoid (CoordinateRing K n r) :=
    (inferInstance : CommRing (CoordinateRing K n r)).toCommSemiring.toAddCommMonoid
  letI : Module K (CoordinateRing K n r) := Algebra.toModule
  letI : CommRing (CoordinateRing K n r ⊗[K] CoordinateRing K n r) := inferInstance
  let q := quotient K n r
  let comulQuotient : Ambient K n →ₐ[K]
      CoordinateRing K n r ⊗[K] CoordinateRing K n r :=
    (Algebra.TensorProduct.map q q).comp
      (Bialgebra.comulAlgHom K (Ambient K n))
  have h : ideal K n r ≤ RingHom.ker comulQuotient.toRingHom := by
    apply Ideal.span_le.mpr
    rintro _ ⟨i, j, hij, hgap, rfl⟩
    apply RingHom.mem_ker.mpr
    change (Algebra.TensorProduct.map q q)
      (Coalgebra.comul (R := K) (entry K n i j)) = 0
    rw [comul_entry K n i j, map_sum]
    apply Finset.sum_eq_zero
    intro index _
    rw [Algebra.TensorProduct.map_tmul]
    by_cases hki : index < i
    · have hz : q (entry K n i index) = 0 := by
        change q (UnitriangularCoordinateRing.quotient K (Fin n)
          (GeneralLinearCoordinateRing.matrix K (Fin n) i index)) = 0
        rw [UnitriangularCoordinateRing.quotient_lower K (Fin n) i index hki, map_zero]
      rw [hz, TensorProduct.zero_tmul]
    · by_cases hei : index = i
      · subst index
        rw [quotient_entry K n r i j hij hgap, TensorProduct.tmul_zero]
      · have hik : i < index := lt_of_le_of_ne (le_of_not_gt hki) (Ne.symm hei)
        by_cases hkj : index ≤ j
        · have hgap' : index.val < i.val + r := lt_of_le_of_lt hkj hgap
          rw [quotient_entry K n r i index hik hgap', TensorProduct.zero_tmul]
        · have hjk : j < index := lt_of_not_ge hkj
          have hz : q (entry K n index j) = 0 := by
            change q (UnitriangularCoordinateRing.quotient K (Fin n)
              (GeneralLinearCoordinateRing.matrix K (Fin n) index j)) = 0
            rw [UnitriangularCoordinateRing.quotient_lower K (Fin n) index j hjk, map_zero]
          rw [hz, TensorProduct.tmul_zero]
  exact RingHom.mem_ker.mp (h hx)

/-- The stage ideal is stable under counit, coproduct and antipode.
Milne, *Algebraic Groups* (2017), §6.49 gives field-case closed subgroups;
the Hopf-ideal argument here works for every commutative base ring. -/
theorem ideal_isHopfIdeal_proof : (ideal K n r).IsHopfIdeal K := by
  refine { counit_eq_zero := ?_, map_mkQ_comul_eq_zero := ?_, antipode_mem := ?_ }
  · intro x hx
    exact counit_zero K n r hx
  · intro x hx
    change (Algebra.TensorProduct.map (quotient K n r) (quotient K n r))
      (Coalgebra.comul (R := K) x) = 0
    exact comul_zero K n r hx
  · intro x hx
    exact antipode_mem K n r hx

instance ideal_isHopfIdeal : (ideal K n r).IsHopfIdeal K :=
  ideal_isHopfIdeal_proof K n r

def quotientBialgHom : Ambient K n →ₐc[K] CoordinateRing K n r :=
  Bialgebra.Quotient.mkBialgHom (ideal K n r)

theorem ideal_le_succ : ideal K n r ≤ ideal K n (r + 1) := by
  apply Ideal.span_le.mpr
  rintro _ ⟨i, j, hij, hgap, rfl⟩
  exact entry_mem K n (r + 1) i j hij (by omega)

theorem ideal_zero : ideal K n 0 = ⊥ := by
  apply le_bot_iff.mp
  apply Ideal.span_le.mpr
  rintro _ ⟨i, j, hij, hgap, rfl⟩
  omega

theorem ideal_one : ideal K n 1 = ⊥ := by
  apply le_bot_iff.mp
  apply Ideal.span_le.mpr
  rintro _ ⟨i, j, hij, hgap, rfl⟩
  omega

/-- The quotient algebra map underlying the closed successor stage. -/
def successor : CoordinateRing K n r →ₐ[K] CoordinateRing K n (r + 1) :=
  Ideal.Quotient.factorₐ K (ideal_le_succ K n r)

end UnitriangularStageCoordinateRing
