/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import AlgebraicGroups.GroupTheory.UpperTriangular
public import AlgebraicGroups.Algebra.GeneralLinearCoordinateRing
public import Mathlib.RingTheory.HopfAlgebra.Quotient

/-!
# The upper-triangular Hopf quotient of the general linear coordinate ring

Only entries below the diagonal are killed in the determinant-localized GL
coordinate algebra. The diagonal entries remain units and the image of the
determinant inverse inverts their product, rather than becoming one. The Hopf
ideal argument uses the GL matrix coproduct and inverse-triangularity over
arbitrary commutative rings, including the zero ring.

## References

* J. S. Milne, *Algebraic Groups* (2017), items 2.8–2.9, pp. 41–42:
  determinant-localized `GL_n` and its upper-triangular subgroup `T_n`
  on commutative algebras.
* Mathlib, `Mathlib/LinearAlgebra/Matrix/Block.lean` for inverse-triangularity
  and the diagonal determinant, and Robert Hawkins's formalization in
  `Mathlib/RingTheory/HopfAlgebra/Quotient.lean` for Hopf ideals.
* `AlgebraicGroups/Algebra/GeneralLinearCoordinateRing.lean` supplies the GL
  Hopf operations; `AlgebraicGroups/Algebra/UnitriangularCoordinateRing.lean`
  supplies the earlier generator-by-generator quotient approach. Here there
  are no diagonal-minus-one relations.
-/

@[expose] public section

noncomputable section

open GeneralLinearCoordinateRing
open scoped TensorProduct

universe u

namespace UpperTriangularCoordinateRing

variable (K : Type u) [CommRing K] (ι : Type u) [Fintype ι] [LinearOrder ι]

/-- A below-diagonal relation in the determinant-localized GL coordinate ring. -/
def relation (i j : ι) : GeneralLinearCoordinateRing.CoordinateRing K ι :=
  if j < i then matrix K ι i j else 0

/-- The ideal generated by the entries strictly below the diagonal. -/
def ideal : Ideal (GeneralLinearCoordinateRing.CoordinateRing K ι) :=
  Ideal.span (Set.range fun p : ι × ι => relation K ι p.1 p.2)

/-- Coordinate algebra of the closed upper-triangular subgroup of GL. -/
abbrev CoordinateRing := GeneralLinearCoordinateRing.CoordinateRing K ι ⧸ ideal K ι

/-- The defining surjection from the actual GL coordinate algebra. -/
def quotient : GeneralLinearCoordinateRing.CoordinateRing K ι →ₐ[K] CoordinateRing K ι :=
  Ideal.Quotient.mkₐ K (ideal K ι)

theorem relation_mem (i j : ι) : relation K ι i j ∈ ideal K ι :=
  Ideal.subset_span ⟨(i, j), rfl⟩

@[simp] theorem quotient_lower (i j : ι) (h : j < i) :
    quotient K ι (matrix K ι i j) = 0 := by
  have hz : quotient K ι (relation K ι i j) = 0 :=
    Ideal.Quotient.eq_zero_iff_mem.mpr (relation_mem K ι i j)
  simpa [relation, h] using hz

/-- The universal GL unit remains a unit in the quotient and is upper triangular. -/
def universal : Matrix.UpperTriangularGroup ι (CoordinateRing K ι) :=
  ⟨Matrix.GeneralLinearGroup.map (quotient K ι).toRingHom
    (GeneralLinearCoordinateRing.universal K ι), by
    intro i j hji
    change quotient K ι (matrix K ι i j) = 0
    exact quotient_lower K ι i j hji⟩

@[simp] theorem universal_apply (i j : ι) :
    (universal K ι).1 i j = quotient K ι (matrix K ι i j) := rfl

theorem universal_diagUnit (i : ι) :
    IsUnit (quotient K ι (matrix K ι i i)) :=
  Matrix.UpperTriangularGroup.isUnit_entry (universal K ι) i

/-- In the coordinates of Milne's `T_n` (item 2.9), the determinant inverse
inverts the product of the diagonal entries; it is not forced to one. -/
theorem universal_detInverse :
    quotient K ι (detInverse K ι) *
      (∏ i, quotient K ι (matrix K ι i i)) = 1 := by
  have hm := congrArg (quotient K ι) (det_mul_detInverse K ι)
  rw [map_mul, map_one, AlgHom.map_det] at hm
  change ((universal K ι).1 : Matrix ι ι (CoordinateRing K ι)).det *
    quotient K ι (detInverse K ι) = 1 at hm
  rw [Matrix.det_of_isUpperTriangular (universal K ι).2] at hm
  rwa [mul_comm] at hm

set_option linter.style.haveILetI false in
/-- The lower-entry relations of Milne's `T_n` (item 2.9) form a Hopf ideal:
the GL coproduct is tested after both quotient maps, and Mathlib's
`Matrix.blockTriangular_inv_of_blockTriangular` handles the antipode through
the inverse of the quotient universal unit. -/
theorem ideal_isHopfIdeal_proof : (ideal K ι).IsHopfIdeal K := by
  let q := quotient K ι
  let comulQuotient : GeneralLinearCoordinateRing.CoordinateRing K ι →ₐ[K]
      CoordinateRing K ι ⊗[K] CoordinateRing K ι :=
    (Algebra.TensorProduct.map q q).comp
      (Bialgebra.comulAlgHom K (GeneralLinearCoordinateRing.CoordinateRing K ι))
  letI : CommRing (CoordinateRing K ι ⊗[K] CoordinateRing K ι) := inferInstance
  have counit_gen (i j : ι) :
      (Bialgebra.counitAlgHom K (GeneralLinearCoordinateRing.CoordinateRing K ι))
        (relation K ι i j) = 0 := by
    by_cases hji : j < i
    · simp only [relation, hji, ↓reduceIte]
      change Coalgebra.counit (R := K) (matrix K ι i j) = 0
      rw [native_counit_matrix]
      simp [ne_of_gt hji]
    · simp [relation, hji]
  have comul_gen (i j : ι) : comulQuotient (relation K ι i j) = 0 := by
    by_cases hji : j < i
    · simp only [relation, hji, ↓reduceIte]
      change (Algebra.TensorProduct.map q q)
        (Coalgebra.comul (R := K) (matrix K ι i j)) = 0
      rw [native_comul_matrix, map_sum]
      apply Finset.sum_eq_zero
      intro index _
      rw [Algebra.TensorProduct.map_tmul]
      by_cases hki : index < i
      · rw [quotient_lower K ι i index hki, TensorProduct.zero_tmul]
      · have hjk : j < index := lt_of_lt_of_le hji (le_of_not_gt hki)
        rw [quotient_lower K ι index j hjk, TensorProduct.tmul_zero]
    · simp [relation, hji]
  have antipode_gen (i j : ι) :
      HopfAlgebra.antipode K (relation K ι i j) ∈ ideal K ι := by
    apply Ideal.Quotient.eq_zero_iff_mem.mp
    by_cases hji : j < i
    · simp only [relation, hji, ↓reduceIte]
      change q (HopfAlgebra.antipode K (matrix K ι i j)) = 0
      have hinv := ((Matrix.GeneralLinearGroup.map q.toRingHom).map_inv
        (GeneralLinearCoordinateRing.universal K ι)).symm
      have hantipode : q (HopfAlgebra.antipode K (matrix K ι i j)) =
          ((universal K ι).1⁻¹ : Matrix.GeneralLinearGroup ι (CoordinateRing K ι)) i j := by
        rw [native_antipode_matrix]
        have heq := congrArg
          (fun g : Matrix.GeneralLinearGroup ι (CoordinateRing K ι) =>
            (g : Matrix ι ι (CoordinateRing K ι)) i j) hinv
        exact heq.symm
      rw [hantipode]
      exact (Matrix.upperTriangularSubgroup ι (CoordinateRing K ι)).inv_mem
        (universal K ι).2 hji
    · simp [relation, hji]
  refine { counit_eq_zero := ?_, map_mkQ_comul_eq_zero := ?_, antipode_mem := ?_ }
  · intro x hx
    have h : ideal K ι ≤ RingHom.ker
        (Bialgebra.counitAlgHom K
          (GeneralLinearCoordinateRing.CoordinateRing K ι)).toRingHom := by
      apply Ideal.span_le.mpr
      rintro _ ⟨⟨i, j⟩, rfl⟩
      exact RingHom.mem_ker.mpr (counit_gen i j)
    change (Bialgebra.counitAlgHom K
      (GeneralLinearCoordinateRing.CoordinateRing K ι)) x = 0
    exact RingHom.mem_ker.mp (h hx)
  · intro x hx
    have h : ideal K ι ≤ RingHom.ker comulQuotient.toRingHom := by
      apply Ideal.span_le.mpr
      rintro _ ⟨⟨i, j⟩, rfl⟩
      exact RingHom.mem_ker.mpr (comul_gen i j)
    exact RingHom.mem_ker.mp (h hx)
  · intro x hx
    have h : ideal K ι ≤ (ideal K ι).comap
        (HopfAlgebra.antipodeAlgHom K
          (GeneralLinearCoordinateRing.CoordinateRing K ι)).toRingHom := by
      apply Ideal.span_le.mpr
      rintro _ ⟨⟨i, j⟩, rfl⟩
      exact antipode_gen i j
    exact h hx

instance ideal_isHopfIdeal : (ideal K ι).IsHopfIdeal K :=
  ideal_isHopfIdeal_proof K ι

instance finiteType : Algebra.FiniteType K (CoordinateRing K ι) :=
  Algebra.FiniteType.of_surjective (quotient K ι) Ideal.Quotient.mk_surjective

end UpperTriangularCoordinateRing
